### ISSUE TITLE
Encode: do not perform rate control for single-tile lossless

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#1009]
Currently, for single tile lossless, rate control is performed, although it is not needed.

This can lead to lossy encoding if there are code passes at the end of a code block that do not
contribute to a rate increase.  The rate control algorithm will remove these code passes,
leading to potential lossy encode.

**Comment by boxerab** [comment]
Correct solution is to include all passes in a single layer for single-layer lossless

**Comment by rouault** [comment]
Do you have examples where that occurs ?

**Comment by boxerab** [comment]
No, I can't remember the exact case, but I saw this happening when I removed the limit of 10 resolution levels. Also, if you look at the logic in the code, you can see how this might happen. 

But, even without a test image, there is no reason to perform rate control on single layer lossless image.
You just need a method to detect when this is the case, and skip the rate control.

**Comment by rouault** [comment]
> Also, if you look at the logic in the code, you can see how this might happen.

Actually I don't see how that could happen. Lossless encoding implies cp->m_specific_param.m_enc.m_disto_alloc == 1 and tcd_tcp->rates[0] == 0. Which implies in opj_tcd_rateallocate() that goodthresh = min; which is the minimum of dd / dr for all passes of all code blocks  ( https://github.com/uclouvain/openjpeg/blob/a55c024fc6b917a409b85aeafd7326421c4aea34/src/lib/openjp2/tcd.c#L616 ). Then opj_tcd_makelayer() is called with this threshold and checks in https://github.com/uclouvain/openjpeg/blob/a55c024fc6b917a409b85aeafd7326421c4aea34/src/lib/openjp2/tcd.c#L291-L292 if (thresh - (dd / dr) < DBL_EPSILON), which should be always true. So all passes should be selected. Am I missing something ?

**Comment by boxerab** [comment]
hmmmm.  Well, I guess that was a false alarm then :)

**Comment by boxerab** [comment]
How about lossless with multiple layers ? Could the final layer be missing some passes ? If so, that would be a problem.

**Comment by rouault** [comment]
The same logic will apply for multiple layers. For lossless encoding, the last layer should have tcd_tcp->rates[layno] == 0, in which case all remaining coding passes will be selected. I just committed a fix for opj_compress help which indicated 1 instead of 0 for this lossless terminating layer

**Comment by boxerab** [comment]
For `-r` flag, 1 indicates a final lossless layer, while for `-q` flag, 0 indicates a final lossless layer.

So, looks like everything is correct then. Closing.

**Comment by rouault** [comment]
> For -r flag, 1 indicates a final lossless layer

Actually that doesn't match my experiments. You really need to set 0 to get all the remaining coding passes in the final layer. 1 gets you almost to lossless, but not completely

**Comment by boxerab** [comment]
Well, what I would do is keep the 1 for compression ratio flag, and then convert to 0 in the code. Compression ratio of 0 is a bit counter-intuitive.  You could let the user know that 1 == final lossless layer.

**Comment by boxerab** [comment]
Also sanity check that rates are decreasing and >= 1

**Comment by boxerab** [comment]
So, I think the key logic to look at is how distortion delta `dd` and rate delta `dr` are handled in rate control. When `dd` and `dr` are both zero (as is the case for passes that do not contribute to rate), these passes are ignored . I guess code assumes that a subsequent layer will include them. But, if this is the final layer, then these passes will be lost.  

So, that's why there should be no rate control at all on final layer, if it is a lossless one. Just include everything and do not look at `dd` and `dr`.

**Comment by rouault** [comment]
OK, https://github.com/uclouvain/openjpeg/commit/b428b8c7e7227cf96c83229df4d7bf009b6d2172 should really make sure to include all passes for a lossless layer

**Comment by boxerab** [comment]
Looks good. You might want to check that only the final layer is specified as lossless by the user.

**Comment by rouault** [comment]
> You might want to check that only the final layer is specified as lossless by the user.

Yes, https://github.com/uclouvain/openjpeg/commit/7aa071aa273aa0b8fafbf055e5eb99b9cb8600a8 will warn about that

**Comment by boxerab** [comment]
Cool.
