### ISSUE TITLE
Openjpeg 2.2.0 always build shared library even though -DBUILD_SHARED_LIBS:bool=off

### ISSUE THREAD

**Issue by xanadu6291** [uclouvain/openjpeg#1019]
Openjpeg 2.2.0 always build shared library even though -DBUILD_SHARED_LIBS:bool=off

Version 2.1.2 is OK.  Is it a bug?

**Comment by rouault** [comment]
> . Is it a bug?

Yes, should be fixed per https://github.com/uclouvain/openjpeg/commit/3dfc6ca2bcf06fd1adb6b6b4cecc6c092f08ba0b

**Comment by pwaller** [comment]
@rouault 

Is there a logic bug in 3dfc6ca? I find that if `-DBUILD_SHARED_LIBS:bool=off` is specified, then the static library does not get installed to `$PREFIX/lib`. (It did get installed prior to 3dfc6ca - that commit appears to have broken our build)

**Comment by rouault** [comment]
@pwaller Indeed. Just fixed it. I probably only tested the "make" target and not the "make install" target.

**Comment by pwaller** [comment]
Confirmed it fixes our build :+1:. A fantastically speedy fix from your side, thanks! :1st_place_medal:
