### ISSUE TITLE
j2k.cpp > comparison of address of 'p_j2k->m_cp.tcps[0].m_data' not equal to a null pointer is always true

### ISSUE THREAD

**Issue by bommo1** [uclouvain/openjpeg#1020]
latest commit. 
Compilation fails with AppleClang 8.1.0.8020042:

j2k.cpp:9244:34: error: comparison of address of 'p_j2k->m_cp.tcps[0].m_data' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
            &p_j2k->m_cp.tcps[0].m_data != NULL) {
             ~~~~~~~~~~~~~~~~~~~~^~~~~~    ~~~~

**Comment by rouault** [comment]
Fixed. Thanks
