### ISSUE TITLE
tcd.cpp>:1617:33: error: assigning to 'OPJ_INT32 *' (aka 'int *') from incompatible type 'void *'

### ISSUE THREAD

**Issue by bommo1** [uclouvain/openjpeg#1021]
latest commit.
Compilation fails with AppleClang 8.1.0.8020042 if compiled with c++:

tcd.cpp>:1617:33: error: assigning to 'OPJ_INT32 *' (aka 'int *') from incompatible type 'void *'
                tilec->data_win = opj_image_data_alloc(l_data_size);
                                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rouault** [comment]
OK, I fixed the issues, but note this is not a supported configuration.

**Comment by bommo1** [comment]
thank you!
I understand. I'll submit a PR next time and you can merge it if you find it appropriate.
