### ISSUE TITLE
Building with Visual Studio 2015

### ISSUE THREAD

**Issue by MartinDavidWaller** [uclouvain/openjpeg#1023]
Hi,

I was wondering if anyone could point me in the right direction with a sample cmake command line to build projects for Visual Studio 2015. I seem to be struggling to get anything to work?

Many thanks

Martin

**Comment by szukw000** [comment]
MartinDavidWaller,
this question must be asked in the openjpeg list, not here.

I use for Visual Studio 2017 and WIN7 and directly using the cl compiler:

```
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE:string="Release" -DBUILD_SHARED_LIBS:bool=on -DCMAKE_INSTALL_PREFIX:path="C:/Users/Public" -DCMAKE_LIBRARY_PATH:path="C:/Users/Public" -DCMAKE_INCLUDE_PATH:path="C:/Users/Public/include" .. 
```

If you do not want directly use the cl compiler, you could use:

```
cmake  -DCMAKE_BUILD_TYPE:string="Release" -DBUILD_SHARED_LIBS:bool=on -DCMAKE_INSTALL_PREFIX:path="C:/Users/Public" -DCMAKE_LIBRARY_PATH:path="C:/Users/Public" -DCMAKE_INCLUDE_PATH:path="C:/Users/Public/include" .. 
```

winfried

**Comment by MartinDavidWaller** [comment]
Many thanks for the reply. I now have it building.
