### ISSUE TITLE
Download and installed code from 2.3 archive. Installing 2.2?

### ISSUE THREAD

**Issue by parker20121** [uclouvain/openjpeg#1030]
I downloaded the 2.3 codebase, compiled it and installed from the openjpeg-v2.3.0-linux-x86_64.tar.gz file. It appears that it's installing 2.2 version of the libraries. 

machine ~/Projects/openjpeg/build $ sudo make install
[ 31%] Built target openjp2
[ 62%] Built target openjp2_static
[ 75%] Built target opj_compress
[ 87%] Built target opj_decompress
[100%] Built target opj_dump
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/openjpeg-2.2/OpenJPEGTargets.cmake
-- Installing: /usr/local/lib/openjpeg-2.2/OpenJPEGTargets-release.cmake
-- Installing: /usr/local/lib/openjpeg-2.2/OpenJPEGConfig.cmake
-- Installing: /usr/local/lib/pkgconfig/libopenjp2.pc
-- Installing: /usr/local/include/openjpeg-2.2/opj_config.h
-- Installing: /usr/local/lib/libopenjp2.so.2.2.0
-- Installing: /usr/local/lib/libopenjp2.so.7
-- Installing: /usr/local/lib/libopenjp2.so
-- Installing: /usr/local/lib/libopenjp2.a
-- Installing: /usr/local/include/openjpeg-2.2/openjpeg.h
-- Installing: /usr/local/include/openjpeg-2.2/opj_stdint.h
-- Installing: /usr/local/bin/opj_decompress
-- Removed runtime path from "/usr/local/bin/opj_decompress"
-- Installing: /usr/local/bin/opj_compress
-- Removed runtime path from "/usr/local/bin/opj_compress"
-- Installing: /usr/local/bin/opj_dump
-- Removed runtime path from "/usr/local/bin/opj_dump"

**Comment by rouault** [comment]
I build and installed from source and it worked fine. You probably didn't build the version you think

**Comment by parker20121** [comment]
I'm talking about from the openjpeg-v2.3.0-linux-x86_64.tar.gz archive listed in the download section. I don't think it contains the right code. I didn't install from the source.

**Comment by parker20121** [comment]
Yeah. My fault.
