### ISSUE TITLE
Trouble compressing large raw image

### ISSUE THREAD

**Issue by rasweet** [uclouvain/openjpeg#1032]
I have a raw image in BIP (RGB,RGB,...) format of width 55722, height 25274, 8 bit precision.  When I attempt to use opj_compress using

\opj_compress -i f:\epsgRGBbip.raw -o epsgCompopj_exact.jp2 -F 55722,25274,3,8,u

I get the error message:

Unable to load raw file

Does opj_compress attempt to read in the entire input file before compressing?  If so, is there any code available to read in just a few lines at a time?  If not, is the compress source code sufficiently modularized that I could modify the input reader rather easily?  (I have done similar mods many times with Kakadu.)

I'm hoping to save myself a lot of trouble, if it is impossible to compress big images with opj_compress.

Thanks,
Roland Sweet

**Comment by rouault** [comment]
Yes, opj_compress cannot handle big input files. Other tools such as gdal_translate from GDAL can use openjpeg to create large JP2 files, provided reasonable tiles are used.

**Comment by rasweet** [comment]
Thank you for the prompt reply.  --  Roland
