### ISSUE TITLE
leaks from cppcheck in lib folder

### ISSUE THREAD

**Issue by maddin200** [uclouvain/openjpeg#1038]
\src\lib\openmj2\mj2.c line 2829 
missing  opj_free(src);

\src\lib\openmj2\mj2_convert.c line 65
missing fclose(f);

all I have found so far

**Comment by ValZapod** [comment]
Fixed 
https://github.com/uclouvain/openjpeg/blob/0bda7188b7b545232a341f1d978b1e4feda46fc2/src/lib/openmj2/mj2.c#L2827

https://github.com/uclouvain/openjpeg/blob/0bda7188b7b545232a341f1d978b1e4feda46fc2/src/lib/openmj2/mj2_convert.c#L65
