### ISSUE TITLE
failing to install latest version of openjpeg from source

### ISSUE THREAD

**Issue by franfcunha** [uclouvain/openjpeg#1041]
Following the instructions from https://github.com/uclouvain/openjpeg/blob/master/INSTALL.md and after:

mkdir build
cd build
cmake .. DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:bool=on 
make 

I have been unable to 

sudo make install given that it throws me ***No rule to make target install. Stop.

Any tip?
Tks

**Comment by rouault** [comment]
Probably something on your side. Note: there's a typo in your command line. You lack a dash sign before DCMAKE_BUILD_TYPE=Release
