### ISSUE TITLE
out of bounds writes

### ISSUE THREAD

**Issue by setharnold** [uclouvain/openjpeg#1077]
https://github.com/uclouvain/openjpeg/blob/da5e897232ef824daf9a492e746ed22cf2a43f18/src/lib/openmj2/mj2.c#L1517

Hello,

Please note that `name[2]` and `name[3]` do not exist.

Thanks

```
    cio_write(cio, tk->urn[urn_num].name[2], 4);
    cio_write(cio, tk->urn[urn_num].name[3], 4);
```

**Comment by mcatanzaro** [comment]
This is basically a duplicate of #1078, the other issue is the same thing a few lines lower in the code. And there is more discussion there.
