### ISSUE TITLE
integer overflow in malloc()

### ISSUE THREAD

**Issue by setharnold** [uclouvain/openjpeg#1082]
https://github.com/uclouvain/openjpeg/blob/06f7d412435ddb62f8e9935af7e306783bc4b75b/src/bin/jp3d/opj_jp3d_compress.c#L401

```
            parameters->tcp_numlayers = numlayers;
            matrix_width = parameters->numresolution[0] + parameters->numresolution[1] + parameters->numresolution[2];
            parameters->cp_matrice = (int *) malloc(numlayers * matrix_width * sizeof(int));
            s = s + 2;
```

Hello, note the `malloc()` argument may suffer from an integer multiplication overflow if these parameters are not bounded elsewhere in the code. I'd like to suggest that all such `malloc(a*b)` calls check their parameters for overflow, or switch to `calloc()`, as appropriate. (With three inputs, this one may take more work than usual.)

Thanks

**Comment by stweil** [comment]
`parameters->numresolution` is `[3, 3, 1]`, so `matrix_width` is 7. Therefore limiting `numlayers` would be sufficient here.

**Comment by setharnold** [comment]
If `matrix_width` is always `7` then this is an easy fix:

- clean up and return an error if `matrix_width != 7`
- use `calloc(numlayers, matrix_width * sizeof(int))`

Thanks
