### ISSUE TITLE
Compilation successful but install unsuccessful: Calling executables throws libraries missing error

### ISSUE THREAD

**Issue by saurabhkm** [uclouvain/openjpeg#1102]
I followed the exact install instruction on the installation page and could successfully build the binaries and they work perfectly in the build folder but on running make install and then calling opj_compress/opj_decompress throws the following error:

opj_compress: error while loading shared libraries: libopenjp2.so.7: cannot open shared object file: No such file or directory

Seems like the make install is not copying the build properly. Please advice.

**Comment by szukw000** [comment]
@saurabhkm ,
1. Which version of openjp2 did you use?
2. Which operating system do you use?
3. Which compiler did you use?
4. Which version of cmake did you use?
winfried

**Comment by saurabhkm** [comment]
Thanks for the response Winfred.
This is for openjpeg2.3 on ubuntu 16.04.
I could fix this by installing libpng and running ldconfig!
I'll go ahead and close this.
