### ISSUE TITLE
HIGH THROUGHPUT JPEG 2000 (HTJ2K)

### ISSUE THREAD

**Issue by Jamaika1** [uclouvain/openjpeg#1112]
Hi
Maybe someone knows where can I download the free HIGH THROUGHPUT JPEG 2000?

**Comment by rouault** [comment]
Github issues are not for questions. Closing

**Comment by stweil** [comment]
Maybe this issue should be reopened (or a new one created). High throughput JPEG 2000 (HTJ2K) is an international standard which promises faster JPEG 2000 (see details at https://htj2k.com/). So supporting that standard might be very interesting for OpenJPEG. Code is available at https://github.com/aous72/OpenJPH.
