### ISSUE TITLE
Sample: encode J2K a data using streams???

### ISSUE THREAD

**Issue by ade90036** [uclouvain/openjpeg#1114]
I have been trying to find a good example (source code) where i could understand the sequence of calls required to successfully encode a data buffer in J2K using streams.

I have found a few example from very old google-groups and using files. 

The API documentation (doxygen) is great if you know what are the sequence of the calls that you need to do, pointless otherwise.

For what i can see there are no tutorials, or the one i have found are dated (v. 1.3.X)

I have also looked at the tests folder but i could find anything that i could follow within a reasonable time. 

What i would like to do is encode a data buffer using J2K and write it to Tiff image using the TiffWriteRawTile. 

Could you point me a good example in your source tree where i could learn how to achieve this?

I suspect that i'm not the only one having this issue, so would you mind updating the README with location of code samples appropriate documentation material for a new starter?

Regards

ade

**Comment by szukw000** [comment]
@ade90036 ,
```
1. You should reconsider your question. You can not 
    'encode a data buffer using J2K and write it to Tiff image'.
    opj_decode -i J2K.file -o TIFF.file
    opj_encode -i TIFF.file -o J2K.file
2. GITHUB is not the place to ask questions. You must use
    https://groups.google.com/forum/#!forum/openjpeg
```
winfried

**Comment by ade90036** [comment]
@szukw00, thanks for the reply. 

 No sure how to interpret your response. 

Yes you can do it / No you cannot? 

The sample you have provided still fundametally read dara from / to file.

I have a uint32 of RGB data and i would like to encode it in J2K, i should be able to do.

Sorry if i havent used the correct channel for asking a question. 

Regardless of this.. documentation need some serious consideration. 

What if that forums shuts down. Or the group ia deleted.

Regards

Ade

**Comment by szukw000** [comment]
@ade90036 ,
please use https://groups.google.com/forum/#!forum/openjpeg to open a thread.
I have some code for creating a JPEG2000 file from a buffer. The buffer is of type
'unsigned char*' but that could be solved.
winfried

**Comment by ade90036** [comment]
@szukw000 , i have created a thread in that forum.

Regards

Ade
