### ISSUE TITLE
Cannot compress PGX into JP3D despite following the directions?

### ISSUE THREAD

**Issue by markehammons** [uclouvain/openjpeg#1134]
I've attempted to create a PGX file with the following characteristics (please tell me if I'm constructing them wrong):

The header has ```PG ML <bitdepth> <width> <height>\n```. I follow the header with intensity values for each pixels represented by bytes (in this case, 8bit, so 1 byte per pixel). I'm writing 512x512 bytes after the header and that's my PGX files. I've written 300 of these for the zplanes of my 3d image, and named them like ```PGX_<zplane number>.pgx``` inside a folder. I then try to convert them into a jp3d file with the command opj_jp3d_compress -i foldername/PGX_*.pgx -o test.jp3d, but the encoder only responds: 
```
[INFO] Infile: 0/PGXs_0000.pgx 
usage: jp3d_vm_enc -i volume-file -o jp3d-file (+ options)
```

What am I doing wrong here?

**Comment by ivatahov** [comment]
I faced the same problem. The solution was to swap the places of the arguments.

` opj_jp3d_compress -o test.jp3d -i foldername/PGX_*.pgx`
