### ISSUE TITLE
Int overflow in jp3d

### ISSUE THREAD

**Issue by ichlubna** [uclouvain/openjpeg#1162]
When compressing a lot of slices (starting from 44 FullHD slices with 3 8bit components in our experiments) the rate values are high enough to cause an int overflow that leads to negative lengths and wrong results.

**Comment by stweil** [comment]
Do you know the exact code location where the overflow occurs?

If the problem can be reproduced, compiling with compiler option `-ftrapv` would help finding the problematic code.
