### ISSUE TITLE
Make fails on Arch Linux

### ISSUE THREAD

**Issue by Jeinzi** [uclouvain/openjpeg#1174]
Hey!

Building a project using OpenJPEG via cmake fails on Arch. I followed the instructions at the end of INSTALL.md:
```cmake
find_package(OpenJPEG REQUIRED)
include_directories(${OPENJPEG_INCLUDE_DIRS})
add_executable(myapp myapp.c)
target_link_libraries(myapp ${OPENJPEG_LIBRARIES})
```
A subsequent make fails, because the included  *openjpeg.h* can't be found. 

As far as I understand it, *OpenJPEGConfig.cmake* defines the variable `SELF_DIR`, and then `OPENJPEG_INCLUDE_DIRS` is defined as `${SELF_DIR}/../../include/openjpeg-2.3`.
That would work out if `SELF_DIR` was */usr/lib/openjpeg-2.3*, but as it turns out `SELF_DIR` is set to */lib64/openjpeg-2.3* whereas */lib64* is a symlink to */usr/lib*. So in the end, `OPENJPEG_INCLUDE_DIRS` is set to */include/openjpeg-3.2* which doesn't exist and the include fails.

Replacing `include_directories(${OPENJPEG_INCLUDE_DIRS})` with `include_directories("/usr/include/openjpeg-2.3")` solves it for the moment.

**Comment by matthew-sharp** [comment]
I've hit this same issue on gentoo.

**Comment by ffontaine** [comment]
I should be noted that this change breaks the cross-compilation of any packages using cmake to find openjpeg (e.g. poppler):

```
PATH="/home/giuliobenetti/autobuild/run/instance-3/output-1/host/bin:/home/giuliobenetti/autobuild/run/instance-3/output-1/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"  /usr/bin/make -j5  -C /home/giuliobenetti/autobuild/run/instance-3/output-1/build/poppler-0.84.0/
make[1]: Entering directory '/home/giuliobenetti/autobuild/run/instance-3/output-1/build/poppler-0.84.0'
make[2]: Entering directory '/home/giuliobenetti/autobuild/run/instance-3/output-1/build/poppler-0.84.0'
make[3]: Entering directory '/home/giuliobenetti/autobuild/run/instance-3/output-1/build/poppler-0.84.0'
Scanning dependencies of target poppler
make[3]: Leaving directory '/home/giuliobenetti/autobuild/run/instance-3/output-1/build/poppler-0.84.0'
make[3]: Entering directory '/home/giuliobenetti/autobuild/run/instance-3/output-1/build/poppler-0.84.0'
[  2%] Building CXX object CMakeFiles/poppler.dir/goo/gbasename.cc.o
[  2%] Building CXX object CMakeFiles/poppler.dir/goo/gbase64.cc.o
arm-linux-g++: ERROR: unsafe header/library path used in cross-compilation: '-isystem' '/usr/include/openjpeg-2.4'
```

The issue is raised because buildroot uses `DESTDIR` to install openjpeg in a dedicated directory (https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html).

Full build log: http://autobuild.buildroot.org/results/e4e/e4e43519a1c70686844b08257971cc350a746636/build-end.log

**Comment by rouault** [comment]
> I should be noted that this change breaks the cross-compilation

any idea how to fix that ?

**Comment by ffontaine** [comment]
I'll test it but I think that the fix would be to revert this commit and call `get_filename_component` with `REALPATH` instead of `ABSOLUTE` (https://cmake.org/cmake/help/latest/command/get_filename_component.html).

**Comment by ffontaine** [comment]
I sent a PR. It works under buildroot but should be tested on arch linux or gentoo.
