### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by robinwangrubin** [uclouvain/openjpeg#1201]
Hello,
I met some trouble when i was installing the openjpeg 

First i downloaded the package from
 `https://github.com/uclouvain/openjpeg/releases/download/v2.3.1/openjpeg-v2.3.1-linux-x86_64.tar.gz`

Then i try to install it, i followed the instruction below:

`https://github.com/uclouvain/openjpeg/blob/master/INSTALL.md`

I wonder ask the package that i downloaded is Binaries?     
Do i need to Compile them? 
If they are Binaries, what should i do ?

**Comment by szukw000** [comment]
@robinwangrubin ,

1. GITHUB is for developers. Your question should be send to the mailing list:
```
https://groups.google.com/forum/#!forum/openjpeg
```
2. Yes, the archive is a binary.
```
tar xvf openjpeg-v2.3.1-linux-x86_64.tar.gz 

openjpeg-v2.3.1-linux-x86_64/lib/libopenjp2.so
openjpeg-v2.3.1-linux-x86_64/lib/libopenjp2.so.2.3.1
openjpeg-v2.3.1-linux-x86_64/lib/pkgconfig/libopenjp2.pc
openjpeg-v2.3.1-linux-x86_64/lib/libopenjp2.a
openjpeg-v2.3.1-linux-x86_64/lib/openjpeg-2.3/OpenJPEGConfig.cmake
openjpeg-v2.3.1-linux-x86_64/lib/openjpeg-2.3/OpenJPEGTargets.cmake
openjpeg-v2.3.1-linux-x86_64/lib/openjpeg-2.3/OpenJPEGTargets-release.cmake
openjpeg-v2.3.1-linux-x86_64/lib/libopenjp2.so.7
openjpeg-v2.3.1-linux-x86_64/bin/opj_dump
openjpeg-v2.3.1-linux-x86_64/bin/opj_compress
openjpeg-v2.3.1-linux-x86_64/bin/opj_decompress
openjpeg-v2.3.1-linux-x86_64/include/openjpeg-2.3/opj_stdint.h
openjpeg-v2.3.1-linux-x86_64/include/openjpeg-2.3/opj_config.h
openjpeg-v2.3.1-linux-x86_64/include/openjpeg-2.3/openjpeg.h
```
3. If you want to compile the library yourself, you must have ZIP and CMAKE installed.
```
GOTO: https://github.com/uclouvain/openjpeg

PRESS: Clone or download

YOU GET: openjpeg-master.zip

SCROLL TO: How to install and use OpenJPEG ?
CLICK ON installation

To follow these 'installation' tips, you have to:

unzip openjpeg-master.zip
```
4. Whether installing the binary archive or the source archive: tell which system you use.

winfried
