### ISSUE TITLE
Slow decoding

### ISSUE THREAD

**Issue by altimadc** [uclouvain/openjpeg#1202]
I am trying to decode j2k images with well over 2000 tiles of size 1024 x 1024
I've tried to parallelize openjpeg as much as possible but it is just too slow compared to commercial image viewers which open the whole thing in seconds. 

Are there any user mods that make decoding faster?

**Comment by ValZapod** [comment]
"which open the whole thing in seconds" Is it bit perfect though? Even Photoshop is very slow.

**Comment by rouault** [comment]
Closing. Too broad

**Comment by ValZapod** [comment]
Can you check it for bit perfect vs Photoshop?
