### ISSUE TITLE
Repair/update Java wrapper, and include in release

### ISSUE THREAD

**Issue by cranphin** [uclouvain/openjpeg#1208]
Hi!

OpenJPEG seems to be pretty much the default Jpeg2000 implementation now.
Sadly for us poor Java developers (who are very bad at c/c++ :) ) there's no current way of using it.

The included wrapper code is outdated, as I understand it doesn't compile, and there's certainly no ready to go binaries included in the release.

Someone has been putting some effort in fixing this, but the results so far are only partial:
https://github.com/ElMostafaIdrassi/OpenJPEGJNI

Is there any hope of actually updating the wrappers, and including binaries for each platform with each release?

Thanks!

**Comment by szukw000** [comment]
@cranphin ,
this OpenJPEGJNI-master has some drawbacks.

1. src/bin/wx/OPJViewer/CMakeLists.txt:

    add_definitions(-DwxUSE_LIBOPENJPEG -DOPENJPEG_VERSION="1.5.0")

    Here you MUST have openjpeg-version.1.5.y installed.

2. compilation error:

    C:\Users\szukw000\LIB\OPENJPEG\OpenJPEGJNI-master-4\wrapping\java\openjp2\JavaOpenJPEGDecoder.c(78): fatal error C1083: Cannot open include file: 'lcms2.h': No such file or directory

    because of wrapping/java/openjp2/CMakeLists.txt:

    if(BUILD_THIRDPARTY)
        include_directories(
            ${LCMS_INCLUDE_DIRNAME}
            ${Z_INCLUDE_DIRNAME}
            ${PNG_INCLUDE_DIRNAME}
            ${TIFF_INCLUDE_DIRNAME}
        )
    endif()

    Here you MUST use BUILD_THIRDPARTY. If not: compilation error.

3. JAVA CMakeLists.txt and JPIP CMakeLists.txt:

    find_package(Java 1.5 REQUIRED)

    error: Target option 1.5 is no longer supported. Use 1.6 or later.

winfried

**Comment by cranphin** [comment]
I've since found: https://github.com/dbmdz/imageio-jnr
This includes a pretty stable and usable binding in Java for openjpeg.

Since this seems a better option then fixing the old Java binding here, I'll close this issue.

_I will leave the suggestion to remove the old binding code (I doubt anyone will fix it), and add some pointers to the mentioned binding, and other bindings, in the readme._

Cheers! :)
