### ISSUE TITLE
compress YUV files to motion jpeg2000 standard

### ISSUE THREAD

**Issue by ShimaMohammadi** [uclouvain/openjpeg#1213]
I have this problem and don't know how to solve it?
'frames_to_mj2' is not recognized as an internal or external command,
operable program or batch file.

**Comment by szukw000** [comment]
@ShimaMohammadi ,
this question is nothing for GITHUB. GITHUB is for developers only. 
You better should use:
```
https://groups.google.com/forum/#!forum/openjpeg
```
An tell which library you have installed on which system. And whether you have installed
it yourself. Here is a hint: 'frames_to_mj' is a command of openjpeg-1.5.

winfried
