### ISSUE TITLE
CMake+VS2017 Compile OK, thirdparty Compile OK, but thirdparty not install

### ISSUE THREAD

**Issue by dbyoung720** [uclouvain/openjpeg#1239]
CMake+VS2017 Compile OK, thirdparty Compile OK, but thirdparty not install

What parameters need to be set?

**Comment by szukw000** [comment]
1. This place is for developers only.
2. Go to : http://openjpeg.org
On the left windown click on ' Mailing-list (subscribe) '
3. Do not forget to show how you did call CMAKE.

winfried
