### ISSUE TITLE
failing to convert 16-bit file: opj_t2_encode_packet(): only 5251 bytes remaining in output buffer. 5621 needed.

### ISSUE THREAD

**Issue by vvizzo** [uclouvain/openjpeg#1243]
OpenJPEG fails to convert 16-bit file (real 16-bit coming from a camera with 16-bit output - PhaseOne IQ3 100MP).

Error message:
opj_t2_encode_packet(): only 5251 bytes remaining in output buffer. 5621 needed.
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194.

The same file converted previously converted to 8-bit goes through without problems - so size is not a problem (ca. 11k x 8k pixels).

Other true 16-bit files are giving similar errors, just different values.

Faux 16-bit (8-bit converted to 16-bit with some blurring) is converted OK - but apparently there is not enough data to create problems.

**Comment by rouault** [comment]
Input file and exact opj_compress command line to reproduce should be provided

**Comment by vvizzo** [comment]
[/cygdrive/c/Users/Mikolaj/Desktop/praca/tif-vs-jpg]$ /usr/local/bin/opj_compress -i szt2230-tif.tif -o szt2230_16bit.jp2

[INFO] tile number 1 / 1
[ERROR] opj_t2_encode_packet(): only 5251 bytes remaining in output buffer. 5621 needed.
[ERROR] Cannot encode tile
failed to encode image: opj_encode
failed to encode image: opj_end_compress
failed to encode image

openjpeg version from master (today)
File available here for a few days (578 MB - if you know other way to transfer it...):
https://we.tl/t-ToDwHBQdMr

Thanks for quick response :)

**Comment by rouault** [comment]
> File available here for a few days

Not sure I'll grab it myself. Was mostly if someone comes after this in "some time". Can the issue be reproduced with a subset of this file ?

**Comment by vvizzo** [comment]
File available here:
http://www.witkacy.hg.pl/szt2230-tif.tif

Either cropping or resizing makes conversion possible, so it looks like it is combination of breadth of image information and size.

(updated original post with new info)

**Comment by kisaa** [comment]
This bug affects other projects using openjpeg (e.g. ImageMagick, Magick.NET) - https://github.com/ImageMagick/ImageMagick/issues/2642. Are there any plans for a new release in the near future to include this fix? Thanks in advance!

**Comment by bbpennel** [comment]
We're running into this issue via imagemagick as well, so I second the request for a release in the near future. Thank you!
