### ISSUE TITLE
Test-suite failure due to hash mismatch

### ISSUE THREAD

**Issue by raghavgururajan** [uclouvain/openjpeg#1264]
**ISSUE:** Tests fail as there are md5 mismatch on numerous non-regression test files.

**OpenJPEG:** v2.3.1

**OpenJPEG-Data:** commit "c5c4a8c"

**ERROR LOG:** [https://bin.disroot.org/?3a9cdd1ebb222254#7KSLEtkR6urHNMjp9ZEM9uPALD4dmWs5pvbRh9MD5XHT](https://bin.disroot.org/?3a9cdd1ebb222254#7KSLEtkR6urHNMjp9ZEM9uPALD4dmWs5pvbRh9MD5XHT)

**SUGGESTED SOLUTION:** Updating hashes in `tests/nonregression/md5refs.txt`

**Comment by rouault** [comment]
The test suite passes fine with master on Travis-CI and AppVeyor. Depending on compilers, environment, some tests are known to fail.

**Comment by raghavgururajan** [comment]
> The test suite passes fine with master on Travis-CI and AppVeyor. Depending on compilers, environment, some tests are known to fail.

I see. I think the tests passes there because the hashes are generated and tested on same machine. If some tests are not reproducible and known to fail, then I think there is no use of having them.
