### ISSUE TITLE
Builds are not reproducible

### ISSUE THREAD

**Issue by agherzan** [uclouvain/openjpeg#1275]
We include this package as part of our software stack but we have requirements for reproducible builds which this package seems to not support. It looks like these binaries encode the build path: 

* opj_compress 
* opj_decompress  
* opj_dump

Can someone give more details on how this gets done in the build metadata and what is the rationale behind it?

**Comment by ValZapod** [comment]
Debian, I suppose, already did fix that.

**Comment by agherzan** [comment]
Closing as no feedback was received.
