### ISSUE TITLE
Building Test Programs

### ISSUE THREAD

**Issue by dms489** [uclouvain/openjpeg#1318]
I have successfully built the and installed the openjpeg library using VS Community 2019 Vserion 16..3. I have, however, been unable to determine how to build and use the test functions included in the test folder. I have attempted repeatedly to get help but nobody is answering. Has support for this software been withdrawn?

**Comment by rouault** [comment]
> Has support for this software been withdrawn?

You can only expect for support if you buy it to someone. As in any open source project, people contribute to this project depending on their own needs, and have no obligation to answer specific requests.
The project has a mailing list ( https://groups.google.com/g/openjpeg ) where you might ask questions

**Comment by dms489** [comment]
Sorry for being a pest, but I want to be clear. I think the JPEG 2000
library could be a breakthrough in a project of mine. I don't want
anyone to do stuff for me. I just need to understand how the test
programs in the "tests" directory are built so that I experiment with
the library. There was a note somewhere in the Wiki saying that the
documentation needs work, and I think my request here might be part of
the missing materials. I have tried several places to get an answer with
no response, hence my initial question. 

DMS

---
David Smith
david.smith@dms489.com 

On 2021-01-05 12:20, Even Rouault wrote:

>> Has support for this software been withdrawn?
> 
> You can only expect for support if you buy it to someone. As in any open source project, people contribute to this project depending on their own needs, and have no obligation to answer specific requests.
> The project has a mailing list ( https://groups.google.com/g/openjpeg ) where you might ask questions 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/uclouvain/openjpeg/issues/1318#issuecomment-754776196
[2]
