### ISSUE TITLE
OpenJPEG is available with EasyConfig

### ISSUE THREAD

**Issue by fizwit** [uclouvain/openjpeg#1319]
For users of EasyBuild OpenJPEG can be installed with LMOD module.

https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/o/OpenJPEG/OpenJPEG-2.4.0-GCCcore-10.2.0.eb

**Comment by rouault** [comment]
Informational content not appropriate for github issues. OpenJPEG is available through lots of distribution channels
