### ISSUE TITLE
Can't find openjpeg.h when cross-compile.

### ISSUE THREAD

**Issue by leimaohui** [uclouvain/openjpeg#1320]
When I upgrade openjpeg2.3.1(57096325457f96d8cd07bd3af04fe81d7a2ba788) to openjpeg2.4.0(37ac30ceff6640bbab502388c5e0fa0bff23f505), I met an issue as following when I compiled an OSS(poppler) which depends on openjpeg:
`fatal error: openjpeg.h: No such file or directory
|    20 | #include <openjpeg.h>
|       |          ^~~~~~~~~~~~
| compilation terminated.
`  
I found it is because the patch of Issue#1174. This patch fixes the include directory to /usr/include/openjpeg-2.4, but under cross-compile environment, openjpeg.h should be installed to "${CROSS_ENV}/usr/include/openjpeg-2.4/" instead of "/usr/include/openjpeg-2.4".

**Comment by rouault** [comment]
Fixed per pull request https://github.com/uclouvain/openjpeg/pull/1321
