### ISSUE TITLE
opj 2.4.0: opj_free missing in opj3d

### ISSUE THREAD

**Issue by malaterre** [uclouvain/openjpeg#1327]
Debian currently remove opj_free:

* https://salsa.debian.org/debian-phototools-team/openjpeg2/-/blob/master/debian/patches/opj_free.patch

This would create a compilation error otherwise.

Thanks for the 2.4.0 release (just in time).

**Comment by ValZapod** [comment]
You can't be serious, Mathieu. D:) It is obvious you need to change to free(), not remove free at all. The problem here is that opj_ is used for libs and this code used to be on libopenjp3d. Now it is not a lib, though.

**Comment by rouault** [comment]
Issue no longer relevant since https://github.com/uclouvain/openjpeg/pull/1350
