### ISSUE TITLE
color of reconstructed png file much darker

### ISSUE THREAD

**Issue by moha23** [uclouvain/openjpeg#1330]
I tried compressing and decompressing an image from the kodak dataset [(kodim01.png)](http://www.cs.albany.edu/~xypan/research/img/Kodak/kodim01.png) but the reconstruction seems much darker no matter what psnr value i give/dont give at all.
Commands I used:

    /home/mo/Documents/openjpeg-v2.4.0-linux-x86_64/bin/opj_compress -i /home/mo/Downloads/kodim01.png -o /home/mo/Downloads/kodim01.jp2
    /home/mo/Documents/openjpeg-v2.4.0-linux-x86_64/bin/opj_decompress -i /home/mo/Downloads/kodim01.jp2 -o /home/mo/Downloads/kodim01recons.png

Is this expected behaviour or am i doing something wrong? When I check the psnr manually it's much lower than what I put in the command. 

[
![Screenshot from 2021-02-03 21-45-58](https://user-images.githubusercontent.com/10138421/106776061-bc332600-6669-11eb-9d24-759d7b9c7bc7.png)
](url)

**Comment by ValZapod** [comment]
The image has Gamma: 2.2 (try exiftool) which darkens the picture on opj_compress. I removed gAMA chunk from the file with 

`pngcrush -m 40  -rem gAMA /mnt/hgfs/Eurovision\ Song\ Contest\ 2019.\ Tel\ Aviv\,\ Israel/kodim01.png /mnt/hgfs/Eurovision\ Song\ Contest\ 2019.\ Tel\ Aviv\,\ Israel/kodim01withoutgAMA.png
`
![kodim01withoutgAMA](https://user-images.githubusercontent.com/31514790/106819974-a6cef380-668b-11eb-8fe1-a5f508f4dc0d.png)

It now works good.

I also quite do not understand why you are not using normal quality of that Kodak test file as was originally present on Photo CD. LOL, here you are:

![IMG0001](https://user-images.githubusercontent.com/31514790/106821748-cd425e00-668e-11eb-9040-fadeeade4e2d.png)

This file has an sRGB chunk that overwrites gAMA and cHRM chunks that are also present. The colors are not 100% correct as we still did not implement PhotoYCC colourspace decoder, but whatever.

**Comment by moha23** [comment]
Oh great! Yeah I tried on a couple other images and it works just fine so figured must be some gamma issue. Thanks a lot for getting back with this detailed info! Just wanted to check out the rate distortion curve for Kodak dataset available online and widely used in research papers. Thanks again.

**Comment by jiuzhuanzhuan** [comment]
> Oh great! Yeah I tried on a couple other images and it works just fine so figured must be some gamma issue. Thanks a lot for getting back with this detailed info! Just wanted to check out the rate distortion curve for Kodak dataset available online and widely used in research papers. Thanks again.

Hi，
 Did you get the correct R-D loss of Kodak compressed with OPENJPEG ? When I try to  compress Kodak lossly，command  as below
 ```
opj_compress -i  kodim01.png  -q  xx  -o kodim01.jp2
opj_decompress -i  kodim01.jp2 -o kodim01recons.png
```
the parameters of `q`  from set of [20,25,30,35,40,45,50].
But the compression rate  of OPENJPEG even bad then jpeg? Did you know how to use OPENJPEG correctly?
