### ISSUE TITLE
error C2169: 'lrintf': intrinsic function, cannot be defined

### ISSUE THREAD

**Issue by NancyLi1013** [uclouvain/openjpeg#1333]
Hi all,

When building openjpeg on Windows with Visual studio 2019 16.9, it failed with the error like this:

`D:\2019\test\buildtrees\openjpeg\src\v2.3.1-ea4b63573b.clean\src\lib\openmj2\opj_includes.h(97): error C2169: 'lrintf': intrinsic function, cannot be defined`

Could you please help take a look?

Thanks in advance!

Related issue https://github.com/microsoft/vcpkg/issues/16645

**Comment by rouault** [comment]
> Could you please help take a look?

Only the openjp2 component is really supported. You are on your own with other components such as openmj2. I would suggest vcpkg only to package openjp2

**Comment by NancyLi1013** [comment]
Thanks for your information @rouault.
 
So there is no plan to support other components except for `openjp2 `, right? If this is true, maybe dropping the support for other components is a good idea.

**Comment by emmenlau** [comment]
Dear @rouault , could you consider the related PR #1339 that should fix this issue?

**Comment by rouault** [comment]
Issue no longer relevant since https://github.com/uclouvain/openjpeg/pull/1350
