### ISSUE TITLE
Guard Bits In CINEMA2K Profile

### ISSUE THREAD

**Issue by anderson1077** [uclouvain/openjpeg#1340]
All CINEMA profiles result in 2 guard bits. SMPTE RDD-52 now specifies 1 guard bit for CINEMA2K and 2 guard bits for CINEMA4K. This appears to be a hard-coded parameter, and would be great to either change it to match the recommendation or make it a user definable parameter.

Also note that RDD-52 also specifies a cblk of 32,32, whereas the default is 64,64. There is already an option to override this.

**Comment by MarcAntoine-Arnaud** [comment]
By doing same as [here](https://github.com/uclouvain/openjpeg/blob/362ec6c92dbc0f563810fafe552e4fa0d9fde024/src/bin/jp2/opj_compress.c#L2217), it's possible to set the guard bits to 1.

I sent a patch on FFmpeg to be able to set this parameter in libopenjpeg encoder.

**Comment by rouault** [comment]
@anderson1077 / @MarcAntoine-Arnaud could you check if https://github.com/uclouvain/openjpeg/pull/1559 fixes the issue?

**Comment by MarcAntoine-Arnaud** [comment]
It's sounds perfect !
I will keep my patch on ffmpeg for now as I not sure to be able to use latest openjpeg version.
