### ISSUE TITLE
New library htjpeg2000

### ISSUE THREAD

**Issue by Jamaika1** [uclouvain/openjpeg#1351]
A new jpeg2000 library has appeared on the official pages. Too bad there are no part16 and part17 parts included. ;)
https://gitlab.com/wg1/htj2k-rs

**Comment by rouault** [comment]
Interesting... I was aware of https://github.com/aous72/OpenJPH

**Comment by rouault** [comment]
HTJ2K read support was added with code ported from OpenJPH per https://github.com/uclouvain/openjpeg/pull/1381
