### ISSUE TITLE
opj_decompress 2.4.0 built with library 2.3.0. 

### ISSUE THREAD

**Issue by John-Nagle** [uclouvain/openjpeg#1352]
Downloaded the **2.4.0** version of OpenJPEG from https://github.com/uclouvain/openjpeg/releases/download/v2.4.0/openjpeg-v2.4.0-linux-x86_64.tar.gz
and extracted opj_decompress. Tried

`opj_decompress -h`

Got

```
This is the opj_decompress utility from the OpenJPEG project.
It decompresses JPEG 2000 codestreams to various image formats.
It has been compiled against openjp2 library **v2.3.0.**
```

Was that executable built with the wrong library?

**Comment by rouault** [comment]
> Was that executable built with the wrong library?

no, but you have likely your system libopenjp2 that is used.

Demo on my system:

$ ldd openjpeg-v2.4.0-linux-x86_64/bin/opj_decompress | grep openjp2
	libopenjp2.so.7 => /lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f6ce0d37000)

$ openjpeg-v2.4.0-linux-x86_64/bin/opj_decompress -h |head -n 4

This is the opj_decompress utility from the OpenJPEG project.
It decompresses JPEG 2000 codestreams to various image formats.
It has been compiled against openjp2 library v2.3.1.

$ LD_LIBRARY_PATH=openjpeg-v2.4.0-linux-x86_64/lib openjpeg-v2.4.0-linux-x86_64/bin/opj_decompress -h |head -n 4

This is the opj_decompress utility from the OpenJPEG project.
It decompresses JPEG 2000 codestreams to various image formats.
It has been compiled against openjp2 library v2.4.0.

The message "has been compiled" is a bit misleading, as it reflects the runtime version, not the build time one

**Comment by John-Nagle** [comment]
Oh, so it's loading an older .so file. Let me look at that. More later.

**Comment by John-Nagle** [comment]
OK, please close; that wasn't the problem. Thanks.
