### ISSUE TITLE
converting .png to .jp2 by opj_compress is different from the original image

### ISSUE THREAD

**Issue by tpdussla93** [uclouvain/openjpeg#1378]
I converted .png image to .jp2 image with opj_compress.exe of release v2.4.0.
(I downloaded the `openjpeg-v2.4.0-windows-x64.zip` at https://github.com/uclouvain/openjpeg/releases/tag/v2.4.0)
And the result jp2 image is a little different from with the original png image.

This is the command that I used for png -> jp2
```
.\opj_compress.exe -i .\Lenna.png -o Lenna.jp2
```
Left image is the original png image and right is converted jp2 image.
![Lenna_compare](https://user-images.githubusercontent.com/32669846/133090629-8663303e-9123-4a36-b010-d4543dd1cc35.png)

When I checked the pixel value, it differs.

I've also attached both files(`Lenna.png` and `Lenna.jp2`) with zip. 
[Lenna.zip](https://github.com/uclouvain/openjpeg/files/7154534/Lenna.zip)

Is it a bug or did I use it wrongly?

I'm not sure, but when I debug it myself, it seems wrong pixel values are read from `pngtoimage`.

Thank you

**Comment by ValZapod** [comment]
Duplicate of #1330

You need to remove sRGB chunk.

pngcrush -m 40 -rem sRGB Lenna.png newLenna.png
![newLenna](https://user-images.githubusercontent.com/31514790/133920554-f052e8af-063e-44cc-9836-b3621e0433c6.png)

**Comment by tpdussla93** [comment]
So, the program cannot decode gAMA, cHRM or sRGB chunks correctly?

I'm able to get the `Lenna.jp2` identical to `Lenna.png` by removing the sRGB chunk.
Thank you.
