### ISSUE TITLE
Color chanel swapping for some JPEG2000 pictures

### ISSUE THREAD

**Issue by nicoinn** [uclouvain/openjpeg#1382]
I believe there is a bug in the colour channel interpretation for the photo attached. 

[dg2img-3f096fe9d00296bc3734ac4f01b5bf60.j2k.zip](https://github.com/uclouvain/openjpeg/files/7379626/dg2img-3f096fe9d00296bc3734ac4f01b5bf60.j2k.zip)

I'm trying to open it from Python and it ends up with swapped color channels --- Pillow or OpenCV will give the same result, both use OpenJPEG under the hood. 

<img width="727" alt="Screenshot 2021-10-20 at 10 48 41" src="https://user-images.githubusercontent.com/2761632/138060730-5585d657-35d1-4d48-bb72-0b804ff95500.png">

To be noted that other JPEG2000 photos open correctly, and that this photo open correctly in many other applications (Preview, Safari). 

This photo comes from a Belgian passport (stored in the biometric chip), and all Belgian passports I could get access to have the same issue. 
In case anyone worries about personal information sharing, this photo is from my passport --- and I hereby grant right to anyone to play with it for the purpose of debugging this issue and nothing else ;)

**Comment by ValZapod** [comment]
@rouault Not our issue, issue happens in jpeg2000 native decoder of ffmpeg, not -c:v libopenjpeg even.

**Comment by ValZapod** [comment]
Patch is there now: https://patchwork.ffmpeg.org/project/ffmpeg/patch/CAB0OVGqQAawMRvTy+-c+zoHGo1UNXdPby_JYi9KtEkemP+AaHA@mail.gmail.com/

**Comment by ValeZAA** [comment]
This is fixed now in https://github.com/FFmpeg/FFmpeg/commit/aab0c23cb848b9db10aae9849505221ba7988776

**Comment by sfarestam-iproov** [comment]
For anyone who finds this later: OpenJPEG decodes this file correctly, as noted above, and the swap comes from Pillow.

The attached file is a JP2, despite its `.j2k` name. Its channel definition (`cdef`) box declares the components as blue, green, red. Pillow decodes tile by tile with `opj_read_tile_header()` and `opj_decode_tile_data()`, which, unlike `opj_decode()`, don't apply the `cdef` box. Pillow didn't apply the box itself either, so red and blue came out swapped.

python-pillow/Pillow#10049 fixes this. With it, Pillow's output for the attached file matches `opj_decompress` byte for byte.
