### ISSUE TITLE
why lossly compression performance worse than jpeg when compress png？

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [uclouvain/openjpeg#1393]
When i compress [24 Kodak pics](http://r0k.us/graphics/kodak/) ，compression ratio even worse than jpeg.
Below is my compression process，

1. convert png to raw by `numpy`
2. use `opj_compress` `opj_decompress`(version==openjpeg-v2.4.0-linux-x86_64)

```
import numpy as np
from PIL import Image
img = np.array(Image.open('kodim01.png'), np.uint8).tofile('kodim01.raw')
opj_compress -i kodim01.raw -F 512,768,3,8,u -I -r 5  -o kodim01.j2k # set r from 5 to 40
opj_decompres -i kodim01.j2k -o kodim01_recon.raw
```
When compareed the R-D performance whith JPEG, openjpeg is worse
![image](https://user-images.githubusercontent.com/40542615/145669427-38d55440-5946-4f78-be3b-caf01f830fc1.png)
（bpp means average bits of pixel  of 24 Kodak pics, psnr means average [Peak Signal to Noise Ratio](https://zh.wikipedia.org/wiki/%E5%B3%B0%E5%80%BC%E4%BF%A1%E5%99%AA%E6%AF%94)  of 24 Kodak pics）.
So, how to set parameters when lossly compress image with public openjpeg  executable correrctly?

**Comment by ValZapod** [comment]
Please test with ffmpeg. Thanks.
