### ISSUE TITLE
pull request - the cinema industry awaits!

### ISSUE THREAD

**Issue by zqqw** [uclouvain/openjpeg#1400]
Dear uclouvain,
cinemas have been using digital technology for some time. Almost everything you see at the cinema is a Digital Cinema Package or DCP. All the trailers, ads, little promo clips, messages and fillers as well as the film itself are all individual DCP's and put together in a playlist. The DCP's are usually provided to the cinemas by the film companies and ad agencies but occasionally it's required to create them to make special content and other tasks like if a trailer is not available or doesn't turn up on time for example. The software used to do this is called dcpomatic. Currently the new version of this requires a small change to openjpeg to meet the latest standards, so it is not in the AUR yet, and the previous version is no longer building due to updates making it outdated, a situation which may well propogate to other distros in time. So while dcpomatic may seem quite obscure, a lot of people go to the cinema and are undoubtedly grateful when it works correctly although they will mostly never even know what DCP's are.
Could you please review this pull request, it looks quite minimal to the casual glance, although I only came across this situation when trying to build dcpomatic and claim no expertise or knowledge regarding "guard bits."  I thought perhaps you could have overlooked the significance and implications of this small change to your code, apologies for disturbing you, while undoubtedly busy with your fine work.
https://github.com/uclouvain/openjpeg/pull/1388/commits

**Comment by ValZapod** [comment]
> Digital Cinema Package or DCP

And yet almost none of you use lossless jpeg 2000! Hey! Why so much lossy?

**Comment by rouault** [comment]
> https://github.com/uclouvain/openjpeg/pull/1388/commits

superseded per https://github.com/uclouvain/openjpeg/pull/1403

**Comment by zqqw** [comment]
Thank you, that looks brilliant, I wondered what effect it would have if the guard bits value was set to a very large number but see you have taken that into account! Hopefully the dcpomatic team will be happy with this and it will allow them to proceed.
Re lossy formats, a DCP for a 2 hour 2D 2K film is around 180GB, a 2 hour 40 minute 2D 4K film is about 285GB in size for example. These take several hours to download. The current Dolby IMS3000 cinema server has 2TB internal storage which can be upgraded to up to 10.5TB with an NAS. But a few TB's soon fills up with these size files! Plus you need some other content about as well. Doubtless as technology progresses quality will increase.
