### ISSUE TITLE
does openjpeg support either visually lossless or numerically lossless jpeg2000 compression?

### ISSUE THREAD

**Issue by tsandio** [uclouvain/openjpeg#1406]
I see in the documentation that openjpeg supports lossless jpeg2000 compression, but what type? Does it support both visually and numerically lossless compression? If so, what parameters should I use during compression?
-Thanks

**Comment by rouault** [comment]
github issues aren't for questions

**Comment by ValZapod** [comment]
There is only one type of lossless, numerical. And yes, of course it does support it.
