### ISSUE TITLE
Cannot determine library version at compile time

### ISSUE THREAD

**Issue by Tjoppen** [uclouvain/openjpeg#1428]
I am currently improving the libopenjpeg binding in FFmpeg and having to resort to configure for figuring out what API calls are available rather than being able to rely on version numbers at compile time. It would be very useful for us and likely others if this information was provided in openjpeg.h moving forward.

**Comment by rouault** [comment]
The version number is provided in opj_config.h: https://github.com/uclouvain/openjpeg/blob/master/src/lib/openjp2/opj_config.h.cmake.in

**Comment by Tjoppen** [comment]
Ah, it was two levels down in the include hierarchy. Thanks
