### ISSUE TITLE
Pixel value could be changed by 0-4 after compression and decompression

### ISSUE THREAD

**Issue by xuemin-liu** [uclouvain/openjpeg#1429]
## Expected behavior and actual behavior.

I made a 16 bit matrix filled with random 12 bit integers. The values in the matrix were changed by 0-4 after compression (quality 100) and decompression. I expect the final matrix should be the same as the original one. 

## Steps to reproduce the problem.

Compress a random 12 bit matrix and decompress the comressed matrix.
Original matrix should be as the same as decmpressed matrix.

## Operating system

Ubuntu

## openjpeg version

2.7-dev

**Comment by ValZapod** [comment]
You mean the image is not lossless when it should be lossless? Did you use lossless compression? Because lossy is not garanteed to be decoded the same, try ffmpeg's jpeg2000, it is better.

**Comment by xuemin-liu** [comment]
@ValZapod  Thanks for you for your comment. That reminded me that the code was actually for lossy compression. 
The problem was in the following code snippet:
`        l_param.tcp_numlayers = 1;
        l_param.cp_fixed_quality = 1;
        l_param.tcp_distoratio[0] = 100;`
It is still lossy compression even distoratio is 100. 
I removed the above code and that fixed my problem.

**Comment by ValZapod** [comment]
Can be closed?
