### ISSUE TITLE
Cannot find openjpeg.h in the /usr/include file!

### ISSUE THREAD

**Issue by wangmiaowei** [uclouvain/openjpeg#1437]
Thanks for your contributions. when I refer to your installation guidances, I succeed but cannot find the openjpeg.h  compiling OpenCV. I check that there is no /usr/include/openjpeg.h in my device. I want to know the reason and could you help me!

**Comment by rouault** [comment]
Check for  /usr/include/openjpeg-2.5/openjpeg.h
