### ISSUE TITLE
Possible bug reading JP2 as grayscale when should be in color

### ISSUE THREAD

**Issue by fmw42** [uclouvain/openjpeg#1464]
### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

The attached image seems to be coded improperly or there is a bug. Can you identify which?

 Exiftool says:

```
 0 ImageHeight                     : 10000
    4 ImageWidth                      : 10000
    8 NumberOfComponents              : 4

but it also says

    3 ColorSpace                      : Grayscale

```

NumberOfComponents I interpret as having 4 channels, RGBI or RGBA, but then it says colorspace is grayscale.  So I am confused about this file. 

### Steps to Reproduce

See above

### Images

http://www.fmwconcepts.com/misc_tests/dop10rgbi_32_280_5652_1_nw_2021.jp2.zip

Original from first file at https://www.opengeodata.nrw.de/produkte/geobasis/lusat/dop/dop_jp2_f10/, but there are a lot of files there that likely have the same issue.

Most tools that I have used (such as GIMP and Photoshop and GraphicConverter) seem to read the file open it as grayscale (with or without) an alpha channel. I believe that is wrong. It should be an RGB with IR channel or perhaps alpha channel, not sure which.

**Are these tools reading it with old JP2 software? Or is this a miscoding on the creator of the files? Or is this a bug in OpenJpeg code for JP2?**

**Comment by rouault** [comment]
The issue is that the value of the EnumCS of the colr box is 17=GreyScale. It should rather be 16=sRGB
```
    <JP2Box name="colr" box_offset="66" box_length="15" data_offset="74" data_length="7">
      <BinaryContent>01000000000011</BinaryContent>
      <DecodedContent>
        <Field name="METH" type="uint8" description="Enumerated Colourspace">1</Field>
        <Field name="PREC" type="uint8">0</Field>
        <Field name="APPROX" type="uint8">0</Field>
        <Field name="EnumCS" type="uint32" description="greyscale">17</Field>
      </DecodedContent>
    </JP2Box>
```

**Comment by rouault** [comment]
by the way recent versions of Kakadu also complain about that file: "Looks like the file contains an illegal channel definitions (cdef) box; trying to fix the problem so that content can still be rendered."

**Comment by fmw42** [comment]
It needs to be coded as RGB not grayscale. Also the 4th channel is coded as alpha an I think it might be IR>
