### ISSUE TITLE
Release v2.5.2 tag is outside of the repository

### ISSUE THREAD

**Issue by klecki** [uclouvain/openjpeg#1521]
## Expected behavior and actual behavior.
Expected behavior: Tag v2.5.2 can be checked out in the clone of this repository.  
Actual behavior: the tag for that release is missing.

A push to the main repo should do?

## Steps to reproduce the problem.
https://github.com/uclouvain/openjpeg/tree/v2.5.2 <- shows that the tag is not pushed to this project

![obraz](https://github.com/uclouvain/openjpeg/assets/8121971/8da60e7b-1226-433f-b894-05c810bad8e9)

It can be also observed by cloning the repository - tag v2.5.2 is missing.

## Operating system

Any

## openjpeg version

v2.5.2.

**Comment by rouault** [comment]
fixed now

**Comment by klecki** [comment]
Thank you @rouault !
