### ISSUE TITLE
Failed to Open a Specific JP2 file

### ISSUE THREAD

**Issue by srinu-kompella** [uclouvain/openjpeg#1544]
## Expected behavior and actual behavior.

Expected Behavior : opj_decode function call should be successful.
Actual Behavior : opj_decode is return OPJ_FALSE, I can see the below log messages in the debug session

Stream too short, expected SOT
Failed to decode tile 23 35
Failed to decode the codestream in the JP2 file

## Steps to reproduce the problem.

Load the attached jp2 file.

## Operating system

window 11

## openjpeg version

2.5.2
[Page.zip](https://github.com/user-attachments/files/16390412/Page.zip)

**Comment by rouault** [comment]
This file is corrupted.
Kakadu also fails on this tile with "Kakadu Core Error:
Missing or out-of-sequence tile-parts for tile number 24 in code-stream!"

**Comment by srinu-kompella** [comment]
@rouault I tried few online viewers, though some viewers are failed, some are able to open this file, when I convert this jp2 file to pdf , intrestingly, adobe is able to convert successfully, can we do something to handle this file here ?
