### ISSUE TITLE
[ERROR] Wrong values for: w(525) h(700) numcomps(0) (ihdr)

### ISSUE THREAD

**Issue by mtjsoft** [uclouvain/openjpeg#1545]
## Expected behavior and actual behavior.

[ERROR] Wrong values for: w(525) h(700) numcomps(0) (ihdr)

## Steps to reproduce the problem.

`.\opj_decompress.exe -i .\temp.jp2 -o .\test.png`

## Operating system

win10

## openjpeg version

v2.5.2

[jp2-img.zip](https://github.com/user-attachments/files/16560327/jp2-img.zip)

**Comment by rouault** [comment]
This file is corrupted. Kakadu also refuses to open it with "Error in Kakadu File Format Support: Malformed image header box (ihdr) found in JP2-family data source.  The box contains fields which do not conform to their legal range."
