### ISSUE TITLE
Can not open libjpeg 

### ISSUE THREAD

**Issue by iivvaall** [uclouvain/openjpeg#1550]
[selfie-min.jpeg.zip](https://github.com/user-attachments/files/16731060/selfie-min.jpeg.zip)
This file is opened in v2.5.0 and not in v2.5.2

git bisect finds https://github.com/uclouvain/openjpeg/commit/0f528e95788863608aa1772f5370659edf618793

steps to reproduce is in https://github.com/python-pillow/Pillow/issues/8327
sorry, I am not a C developer

**Comment by rouault** [comment]
I don't think this is an OpenJPEG bug (cf https://github.com/python-pillow/Pillow/issues/8327#issuecomment-2307414482)
