### ISSUE TITLE
T1 optimisations jpeg2000

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#172]
Originally reported on Google Code with ID 172

```
Hi all,

Here are some patches to openjpeg 1.5 which speed up the T1 encoding a bit:

http://carlh.net/software/openjpeg

On the plus side, encoding a large (1998x1080) image takes about 75% of the time with
the patches compared to the release openjpeg (and the result is bitwise identical).

Caveats: no speed-up to decoding, and very limited regression testing.

It's a work in progress, so it's a bit rough round the edges.

Comments welcome.
```

Reported by [malaterre](https://github.com/malaterre) on 2012-08-29 06:59:59

**Comment by rouault** [comment]
openjpeg-2.1.0-t1-enc.patch can be found in
http://storage.googleapis.com/google-code-attachments/openjpeg/issue-172/comment-7/openjpeg-2.1.0-t1-enc.patch (referenced from original Google issue https://code.google.com/archive/p/openjpeg/issues/172)

**Comment by rouault** [comment]
On MAPA.tif 13498x9944 3 bands 8bit depth, opj_compress goes from 68 s (user time) on bare 2.1.0 to 61 s on 2.1.0+openjpeg-2.1.0-t1-enc.patch, so 10% decrease.
On 8c05f00a-ae05-4dd5-bdc7-a1b5eed4ebfb.tif 15595x111128 3 bands 8bit depth, opj_compress goes from 83s to 75s, so 10% decrease too
