### ISSUE TITLE
CMAP: MTYP == 0 (direct use) not handled properly

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#235]
Originally reported on Google Code with ID 235
```
The attached file appears blurred in openjpeg-2.0 because the final tile part is higher
than expected and so opj_j2k_read_sot exits too early.

I have attached a patch to resolve this.
```

Reported by [slmistry](https://github.com/slmistry) on 2013-09-06 22:04:47

<hr>
 * *Attachment: [blur.patch](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-235/comment-0/blur.patch)*
 * *Attachment: [Bug691816.pdf](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-235/comment-0/Bug691816.pdf)*

**Comment by detonin** [comment]
@mayeut the test you added is failing on myside ... Is this expected?
http://my.cdash.org/viewTest.php?onlydelta&buildid=796186

**Comment by mayeut** [comment]
@detonin,

I've seen this. I forgot to add the dump for issue235.jp2, it's fixed.
