### ISSUE TITLE
OpenJPEG doesn't compile on mac with gcc 4

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#243]
Originally reported on Google Code with ID 243
```
Several methods are forward declared as static but the actual definition does not have
the static keyword (gcc4 with our build options chokes on this).

This was reported in OpenJPEG 2.0.0
MacOSX 10.7.5
Xcode 3.2.6

Attached patch is generated with diff.


```

Reported by `brta.enfocus` on 2013-10-08 12:29:48

<hr>
 * *Attachment: [fix gcc 4 compile errors](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-243/comment-0/fix gcc 4 compile errors)*

**Comment by mayeut** [comment]
Should be fixed but I can't verify this with my compiler.
