### ISSUE TITLE
OpenJPEG writes to stderr

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#246]
Originally reported on Google Code with ID 246
```
OpenJPEG has a nice system for people that don't want messages being logged to stdout/stderr.
Unfortunatly this system wasn't used yet everywhere.

Attached patch replaces printf by opj_event_msg where possible (and removes some logs
completely where it doesn't seem to make sense).

Patch was created using diff on OpenJPEG 2.0.0

```

Reported by `brta.enfocus` on 2013-10-08 12:39:31

<hr>
 * *Attachment: [remove remaining printf](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-246/comment-0/remove remaining printf)*

**Comment by mayeut** [comment]
@detonin, @malaterre,

There should't be any printf in stdout/stderr except in some j2k_dump_image* functions with a specific flag. If that's ok, issue can be closed.

**Comment by detonin** [comment]
Thanks. Closing then.
