### ISSUE TITLE
read: segment too long (6182) with max (35872) for codeblock 0 (p=19, b=2, r=5, c=1)

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#284]
Originally reported on Google Code with ID 284

```
The attached file (see issue 135 for construction) fails to decode in current openjpeg:

read: segment too long (6182) with max (35872) for codeblock 0 (p=19, b=2, r=5, c=1)
[ERROR] Failed to decode.
[ERROR] Failed to decode tile 1/1
ERROR -> opj_decompress: failed to decode image!

```

Reported by [malaterre](https://github.com/malaterre) on 2014-03-12 15:40:04

<hr>
- _Attachment: [issue135.trans.j2k](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-284/comment-0/issue135.trans.j2k)_

**Comment by tfmorris** [comment]
I have no idea if the above analysis is correct, but just to update the references:
r2262 == commit b65bf4836933355df88a9eb5ce5696dcf3c324ba

Code snippet above in diff: https://github.com/uclouvain/openjpeg/commit/b65bf4836933355df88a9eb5ce5696dcf3c324ba#diff-1bfcd820328c9d73ee9052a650febf3eR1114

Code snippet in current master: https://github.com/uclouvain/openjpeg/blob/master/src/lib/openjp2/t2.c#L1191

**Comment by tfmorris** [comment]
I have additional images that demonstrate this problem if it would help with the debug.  JPEG2000 is used extensively by the Internet Archive and OpenJPEG only appears to be able to decode about half the pages there.  The `kdu_expand` program doesn't have an issue with them.

**Comment by tfmorris** [comment]
Oops! Ignore my comment.  My problem was due to an problem further upstream in the processing pipeline which was feeding truncated JP2K data to OpenJPEG. Now `opj_decompress` seems to be working find as a drop-in replacement for `kdu_expand`.

**Comment by rouault** [comment]
From latest comment, closing as not a bug
