### ISSUE TITLE
Need to make sure ABI changed

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#306]
Originally reported on Google Code with ID 306
```
Need to run abi compliance checker to confirm ABI changed in 2.1
```

Reported by [malaterre](https://github.com/malaterre) on 2014-03-24 14:45:25

**Comment by mayeut** [comment]
c.f. #600

**Comment by detonin** [comment]
ABI changed indeed in 2.1.
New upcoming release 2.1.1 does not introduce any ABI break compared to 2.1 though.

**Comment by lvc** [comment]
Report: http://www.openjpeg.org/abi-check/timeline/openjpeg/
