### ISSUE TITLE
Bug in jp2.c of openjpeg-branch15-r2833

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#335]
Originally reported on Google Code with ID 335

```
./j2k_to_image -i beach_64bitsbox.jp2 -o beach.png

[ERROR] Integer overflow in box->length
[ERROR] Failed to decode jp2 structure
ERROR -> j2k_to_image: failed to decode image!

The error message is reported in jp2_read_boxhdr().

'beach_64bitsbox.jp2' contains an 'XML' box that
is not skipped.

./j2k_to_image -i beach_64bitsbox.jp2 -o beach.png

[INFO] tile 1 of 1
[INFO] - tiers-1 took 0.015000 s
[INFO] - dwt took 0.001000 s
[INFO] - tile decoded in 0.017000 s
Successfully generated Outfile beach.png

The patch is attached. It skips at least one 'XML' box.

winfried



```

Reported by [szukw000](https://github.com/szukw000) on 2014-04-09 01:10:18

<hr>
- _Attachment: [openjpeg-1.5.x-branch-r2835-1-xml.dif.gz](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-335/comment-0/openjpeg-1.5.x-branch-r2835-1-xml.dif.gz)_

**Comment by detonin** [comment]
Closing, as 1.x version is not maintained anymore.
If you need this issue resolved, please switch instead to latest version where its is likely already fixed.
https://groups.google.com/d/msg/openjpeg/w2I6qPOw_KA/S85qgiy_AgAJ
