### ISSUE TITLE
Feature: Add OpenMP support

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#372]
Originally reported on Google Code with ID 372

```
OpenMP will allow the library to use all available cores.
On my quad core system, OpenMP decreases encode and decode times
by about 40%.

Patch to follow shortly.

```

Reported by [boxerab](https://github.com/boxerab) on 2014-07-05 18:27:54

**Comment by rouault** [comment]
Multi-threading support is now in trunk (not using openmp, but custom win32 thread/pthread)
