### ISSUE TITLE
Add images from various security issues to test suite

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#415]
Originally reported on Google Code with ID 415
```
The issue is restricted to Coreteam as it contains data from restricted issues.

Add images from :
issue 362
issue 363
issue 390
issue 391
issue 400
issue 413

Please add attached images to http://openjpeg.googlecode.com/svn/data/input/nonregression/

Patch provided for data & trunk for test updates
```

Reported by [mayeut](https://github.com/mayeut) on 2014-10-17 18:24:09

<hr>
 * *Attachment: [issue362-2863.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue362-2863.jp2)*
 * *Attachment: [issue362-2866.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue362-2866.jp2)*
 * *Attachment: [issue362-2894.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue362-2894.jp2)*
 * *Attachment: [issue363-4723.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue363-4723.jp2)*
 * *Attachment: [issue363-4740.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue363-4740.jp2)*
 * *Attachment: [issue363-4792.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue363-4792.jp2)*
 * *Attachment: [issue390.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue390.jp2)*
 * *Attachment: [issue391.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue391.jp2)*
 * *Attachment: [issue400.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue400.jp2)*
 * *Attachment: [issue413.jp2](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-415/comment-0/issue413.jp2)*

**Comment by mayeut** [comment]
Other images shall be uploaded using original issue number.
Closing.
