### ISSUE TITLE
Multiple warnings when building OpenJPEG (trunk)

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#442]
Originally reported on Google Code with ID 442

```
c.f. DashBoard http://my.cdash.org/index.php?project=OPENJPEG

There should be no warning when building OpenJPEG

```

Reported by [mayeut](https://github.com/mayeut) on 2014-11-24 21:25:27

**Comment by rouault** [comment]
Building with the base configuration and without third-parties is warning free. Closing
