### ISSUE TITLE
Image in pdf don't display

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#447]
Originally reported on Google Code with ID 447
```
What steps will reproduce the problem?
1. Open the attached document in chrome
2. Image on page 11 is black

This issue is from 
https://code.google.com/p/chromium/issues/detail?id=437549

```

Reported by `bo_xu@foxitsoftware.com` on 2014-12-04 18:20:16

<hr>
 * *Attachment: [community-amenity-contributions-through-rezonings-policy.pdf](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-447/comment-0/community-amenity-contributions-through-rezonings-policy.pdf)*

**Comment by szukw000** [comment]
@mayeut , @detonin , all images of issue #447 (0.jp2 ... 8.jp2) are broken.

All images have an ihdr, a colr and a pclr box inside jp2h, but a cmap box outside jp2h.

KDU refuses to show: "JPX source contains a codestream with a palette (pclr) box, but
no component mapping (cmap) box. This illegal situation ..."

winfried
