### ISSUE TITLE
Various memory access issues found via fuzzing

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#448]
Originally reported on Google Code with ID 448

```
The attached files will expose memory access issues in openjpeg (tested with opj_decompress
on latest svn code).

sample2.j2k will crash opj_decompress, the other two (sample0.j2k, sample1.j2k) can
only be seen when using additional debugging tools like valgrind or address sanitizer.
I'll attach address sanitizer output for further analysis.
```

Reported by `hanno@hboeck.de` on 2014-12-04 18:52:36

<hr>
- _Attachment: [sample0.j2k](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample0.j2k)_
- _Attachment: [sample0.asan.log](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample0.asan.log)_
- _Attachment: [sample1.j2k](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample1.j2k)_
- _Attachment: [sample1.asan.log](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample1.asan.log)_
- _Attachment: [sample2.j2k](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample2.j2k)_
- _Attachment: [sample2.asan.log](https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample2.asan.log)_

**Comment by rouault** [comment]
@detonin Could you attach https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample0.j2k , https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample1.j2k , https://storage.googleapis.com/google-code-attachments/openjpeg/issue-448/comment-0/sample2.j2k here ? (permission denied for me)

**Comment by detonin** [comment]
Most of the google code issues are still available (and the IDs correspond to the github ones) but this is apparently not the case for the issues that were marked as "private" in Google Code, like this one. Unfortunately, I do not know at this point a way to login back into Google Code to get access to it.
https://code.google.com/archive/p/openjpeg/

**Comment by rouault** [comment]
Google answer to our request to access those tickets : """ Unfortunately the Google Code Archive only 
contains public project data, so restricted-access issues are no longer 
available."""

So closing as there's nothing actionable anymore... Hopefully those issues have been spotted by other people doing fuzzing or will be by OSS-Fuzz
