### ISSUE TITLE
Forward discrete wavelet transform: implement periodic symmetric extension at boundaries

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#452]
Originally reported on Google Code with ID 452
```
According to the final draft
of 15444-1, section F.2 (normative), the inverse wavelet transform must
use periodic symmetric extension at boundaries. 

I assume that this is also required for the forward wavelet.

However, openjpeg code truncates at the boundaries:

#define OPJ_S_(i) ((i)<0?OPJ_S(0):((i)>=sn?OPJ_S(sn-1):OPJ_S(i)))
#define OPJ_D_(i) ((i)<0?OPJ_D(0):((i)>=dn?OPJ_D(dn-1):OPJ_D(i)))

Symmetric extension should reduce boundary artifacts.





```

Reported by [boxerab](https://github.com/boxerab) on 2014-12-18 21:35:09

**Comment by boxerab** [comment]
The above macros implement clamping on odd/even samples at each lifting step -this is equivalent to symmetric extension past the boundaries. Please close this issue.

**Comment by detonin** [comment]
Thanks Aaron for digging into this yourself (and special thanks to Prof Taubman for having explained this on the kakadu list :-)). So OpenJPEG is (still) conformant to JPEG 2000 standard, good news !
@malaterre: openjpeg correctly implements symetric extension.
