### ISSUE TITLE
g4_colr.j2c not handled properly

### ISSUE THREAD

**Issue by mayeut** [uclouvain/openjpeg#532]
As per dashboard g4_colr.j2c is not handled properly:
http://my.cdash.org/testSummary.php?project=237&name=ETS-KDU-g4_colr.j2c-compare2ref&date=2015-07-11

**Comment by mayeut** [comment]
@detonin , @malaterre ,
I think this is most likely related to #470 (revisited) as the first Zppt is 100, decreasing for each PPT marker.

**Comment by mayeut** [comment]
The file is decoded nicely with my commit. Thus, I added non regression data (which did not exist).

**Comment by detonin** [comment]
@mayeut Thanks this could be closed then as soon as PR 533 is merged.
