### ISSUE TITLE
PNG images are always read as RGB(A) images

### ISSUE THREAD

**Issue by mayeut** [uclouvain/openjpeg#536]
Even with grayscale images, PNG images are always read as color images

**Comment by szukw000** [comment]
@mayeut , can you point to one or two of these PNG grayscale images?

winfried

**Comment by mayeut** [comment]
@szukw000 ,

Here you go, from png test suite 1st with an alpha channel (basn4a08), 2nd without (basn0g08).
![basn4a08](https://cloud.githubusercontent.com/assets/9768336/8758168/3c2e5848-2ce1-11e5-9546-2ea9bf161f20.png)
![basn0g08](https://cloud.githubusercontent.com/assets/9768336/8758178/6515dff6-2ce1-11e5-8fdf-af4948b297f2.png)

It's clearly written in pngtoimage:
````c
/* GRAY => RGB; GRAY_ALPHA => RGBA */
if(color_type == PNG_COLOR_TYPE_GRAY || color_type == PNG_COLOR_TYPE_GRAY_ALPHA)
{
  png_set_gray_to_rgb(png);
  color_type = (color_type == PNG_COLOR_TYPE_GRAY? PNG_COLOR_TYPE_RGB:
                                                    PNG_COLOR_TYPE_RGB_ALPHA);
}
````

**Comment by mayeut** [comment]
@szukw000,

those images are from libpng-1.6.13/contrib/pngsuite

**Comment by szukw000** [comment]
@mayeut ,
3 channels GRAY give GRAY, 3 channels COLOR give COLOR.

COLOR:
basn6a08.png
basn6a16.png
ftp0n2c08.png

GRAY:
basn4a08.png
basn0g08.png

winfried

**Comment by mayeut** [comment]
@szukw000 ,

There's no such thing as 3 channels grayscale image. It's a color image with R == G == B (or Y == Y, U == V ==0, ....). It still appears gray but should only get 1 channel, no need to compress 3 components (that are identical).
To be linked with #264
