### ISSUE TITLE
NR-JP2-file5.jp2-compare2base fails with third party libcms

### ISSUE THREAD

**Issue by mayeut** [uclouvain/openjpeg#540]
@detonin,

All is in the title. I see on CDash that you're not using ThirdParty. What version of libcms are you using ?

**Comment by detonin** [comment]
@mayeut 
I'm using the one from macports:

lcms2 @2.6 (graphics)
Variants:             universal
Description:          LCMS is the Little Color Management System, a portable Color Matching Method (CMM) library which implements fast transforms between ICC profiles. Color management refers to techniques that ensure consistent color as images are transferred from scanners or cameras to monitors and printers.
Homepage:             http://www.littlecms.com/
Library Dependencies: jpeg, tiff, zlib
Platforms:            darwin
License:              MIT
Maintainers:          nomaintainer@macports.org

**Comment by detonin** [comment]
Strange: even if I enable thirdparty, it still uses my macports library

**Comment by mayeut** [comment]
Same for NR-DEC-issue171.jp2-71-decode-md5

**Comment by mayeut** [comment]
@detonin,

With 2.6 I get the same results, with 2.7 (latest) results changed again.
I will push 2.6 on master for now. Master was using 2.1 till now.

**Comment by mayeut** [comment]
@detonin,

Either we close this issue & dismiss #544 or (& I think it's best), Merge #544 & update data

**Comment by julienmalik** [comment]
Current master of lcms has a fix for all the misaligned address reported by UBSan, but the patch does not appear to be in 2.7...

**Comment by julienmalik** [comment]
I bet that's the one we want to clean up ubsan reports : https://github.com/mm2/Little-CMS/commit/40c640365214587d6f61161a738ade93ccba25c8

**Comment by mayeut** [comment]
I'll update the PR to mm2/Little-CMS@0e8234e090d6aab33f90e2eb0296f30aa0705e57
