### ISSUE TITLE
missing libopenjpeg.pc in 1.5.2

### ISSUE THREAD

**Issue by dunn** [uclouvain/openjpeg#562]
In 1.5.1, `libopenjpeg.pc` existed as a symlink to `libopenjpeg1.pc`, but that symlink has been removed in 1.5.2, breaking some builds that use `pkg-config libopenjpeg`.

**Comment by detonin** [comment]
Closing, as 1.x version is not maintained anymore.
If you need this issue resolved, please switch instead to latest version where its is likely already fixed.
https://groups.google.com/d/msg/openjpeg/w2I6qPOw_KA/S85qgiy_AgAJ
