### ISSUE TITLE
Backport bugfixes from git/master to 1.5 branch

### ISSUE THREAD

**Issue by detonin** [uclouvain/openjpeg#574]
compile bugfixes since last release and backport

**Comment by szukw000** [comment]
@detonin,

I have sent a patch for openjpeg-1.5.x-branch-r3007 to the list:

    [OpenJPEG] patch for openjpeg-1.5.x-branch-r3007

winfried

**Comment by malaterre** [comment]
Please backport patch from #571

**Comment by detonin** [comment]
@szukw000 The patch you sent modifies jpip code, which is low-priority for the 1.5.3 release. Please open a Pull Request if needed. (I fixed the "unsupported platform" error and will push it soon).

**Comment by detonin** [comment]
I updated tests for 1.5 branch with the ones from master and would like to fix critical bugs to release 1.5.3 (no new features).

I'll fix #571 .

If you see any other bugfix that should be backported not yet listed here:
https://github.com/uclouvain/openjpeg/milestones/OPJ%20v1.5.3
Please let me know in this thread.

**Comment by malaterre** [comment]
Antonin, I've pushed:

[openjpeg-1.5 4469a98] Wrong TGA header generated by j2k_to_image

This was reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777636#10

**Comment by detonin** [comment]
Closing, as 1.x version is not maintained anymore.
If you need this issue resolved, please switch instead to latest version where its is likely already fixed.
https://groups.google.com/d/msg/openjpeg/w2I6qPOw_KA/S85qgiy_AgAJ
