### ISSUE TITLE
Add Coverity Scan analysis

### ISSUE THREAD

**Issue by mayeut** [uclouvain/openjpeg#580]
GitHub, travis-ci & Coverity Scan work well together.
OpenJPEG should make full use of this by adding Coverity Scan analysis to find defect as soon as possible.

**Comment by detonin** [comment]
coverity just fixed sth that prevented settings to be updated to link to the new github repo. Integration with github and travis should work now.

**Comment by detonin** [comment]
Btw, they recommend to create a coverity branch where we merge when we want to trigger a scan, rather than triggering a scan for each and every commit.
https://scan.coverity.com/travis_ci

**Comment by mayeut** [comment]
@detonin,

It seems that the link between coverity & GitHub is not done.
Project Settings in Coverity shows that a link should be done.
I can't do this as I have no Admin access to the repo (I guess, the error is cryptic when I click submit). Could you do that please ?

**Comment by detonin** [comment]
@mayeut ,
Yes I did it too but nothing seems to happen. I get the following error:
Failed to link project. Name contains invalid characters.

I'll dig into this or contact the support again if i don't solve this myself.

**Comment by detonin** [comment]
I changed the name in coverity to fix previous issue but now there is no github integration link button anymore. I'll contact the support

**Comment by detonin** [comment]
waiting for coverity support to answer

**Comment by detonin** [comment]
No answer from support.
I've re-created a project directly linked with github.
Configuring travis-ci should work now with instructions found in "Configure Travis-CI" tab, on the page reached when clicking "submit a build".

**Comment by mayeut** [comment]
What cmake options shall be enabled ?

- BUILD_CODEC
- BUILD_THIRDPARTY

**Comment by detonin** [comment]
I would recommend these two options only for now.
MJ2, JPIP, and JPWL are (still) obsolete in master and I did not yet take a decision on the future of these features. Comments welcome btw.

**Comment by mayeut** [comment]
This is done for some time now.

**Comment by stweil** [comment]
@detonin, @mayeut, I suggest updating https://scan.coverity.com/projects/uclouvain-openjpeg. There were a lot of code changes since the last version which is covered by Coverity scan (September 2016).
