### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [uclouvain/openjpeg#587]
I would like to point out that identifiers like "[`__FIX_H`](https://github.com/uclouvain/openjpeg/blob/2d24b6000d5611615e3e6d799e20d5fdbe4e2a1e/src/lib/openjp3d/fix.h#L35)" and "[`__IMAGE_H`](https://github.com/uclouvain/openjpeg/blob/2d24b6000d5611615e3e6d799e20d5fdbe4e2a1e/src/lib/openjp2/image.h#L31)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/uclouvain/openjpeg/commit/13cde9fa37249628af6b6f10601b733f87a025f4 "Renaming of some include guards").

Are there [a few update candidates left over](https://github.com/uclouvain/openjpeg/blob/3aaeea7ce8c2065d29483817b7fd07226601851c/thirdparty/libtiff/tiff.h#L27 "Remaining update candidates")?

**Comment by rouault** [comment]
Regarding thirdparty code, the issue should be first resolved upstream, and then openjpeg would resync with it

**Comment by elfring** [comment]
* How do you think about to inform corresponding contributors for the other software components?
* How much can you trigger further software improvements?

**Comment by rouault** [comment]
> How do you think about to inform corresponding contributors for the other software components?

Well, research about the other projects to know who their developers are, bug trackers, mailing list, etc. For example for libtiff : http://www.simplesystems.org/libtiff/

> How much can you trigger further software improvements?

Sorry, I didn't understand what you meant.

Anyway thirdparty code is a bit second citizen (in my humble opinion), since for example Linux distributions will not compile it but rely on the external libraries

**Comment by elfring** [comment]
>Well, research about …

I assumed that you might have a better contact to the other contributors already.


>Sorry, I didn't understand what you meant.

* Should this issue be reopened until the companion components will also be fixed anyhow?
* Would you like to update any relationships with bundled software?
