### ISSUE TITLE
Package 'openjp2', required by 'libopenjpip', not found

### ISSUE THREAD

**Issue by malaterre** [uclouvain/openjpeg#594]
libopenjpip.pc has unsatisfied dependencies:

$ pkg-config --exists --print-errors libopenjpip
Package openjp2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `openjp2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'openjp2', required by 'libopenjpip', not found

**Comment by malaterre** [comment]
Orig reg: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787383

**Comment by malaterre** [comment]
`Requires: openjp2` should maybe read as `Requires: libopenjp2`

**Comment by malaterre** [comment]
ping ?

**Comment by stweil** [comment]
@malaterre, I just sent pull request #795 which should fix that. Maybe you want to review / test it.

**Comment by malaterre** [comment]
@stweil looks good to me :+1:
