### ISSUE TITLE
Logical condition

### ISSUE THREAD

**Issue by maddin200** [uclouvain/openjpeg#596]
jpwl.c line 1299
always evaluates to true
(!JPWL_ASSUME || JPWL_ASSUME)

**Comment by malaterre** [comment]
This was introduced at commit 7fd2ae97. @fodevaux any way we can contact original authors ?

**Comment by malaterre** [comment]
this code is never compiled, must have been found by some dummy static code analyzer. I am tempted to close as wontfix.

**Comment by maddin200** [comment]
Maybe it can be commented as unused code.
