### ISSUE TITLE
Add API/ABI tracker

### ISSUE THREAD

**Issue by detonin** [uclouvain/openjpeg#600]
Add tracker from Andrey Ponomarenko
https://github.com/lvc/abi-tracker

@mayeut Do you think this could be added to travis (or do we keep this for the jenkins server) ?

# Email from Andrey - 16/09/2015

I'm glad to inform you that the open-source implementation of the Linux Upstream Tracker is ready. It's available at: https://github.com/lvc/abi-tracker

It would be great if you can host and support the tracker for the OpenJPEG library somewhere and make reports public for the Linux community.

You can download the starter package with reports for all past releases of the OpenJPEG library and configuration files for x86_64 here: http://abi-laboratory.pro/files/openjpeg-abi-tracker.tar.gz

I've put the README file into the package with detailed instructions on how to setup the ABI tracker for the OpenJPEG library. It's easy. You only need to generate reports for the future releases of the library. The index file of the report is in the timeline/openjpeg/ subdirectory of the package.

I will redirect the old unsupported page of the tracker for OpenJPEG at upstream-tracker.org to your site if you'll decide to host the tracker.

# Answer from Andrey - 17/09/2015

I have no experience with travis. But this is a good idea!

The ABI monitor and ABI tracker tools are designed to automatically download, build and analyze packages from the github repo of the library. The ABI monitor downloads and builds packages and then generates the configuration file (openjpeg.json, it is included in the package) for the ABI tracker to create ABI timeline report. This can be done by two commands:

abi-monitor -get -build openjpeg.json # download and build library versions
abi-tracker -build openjpeg.json # build ABI timeline report

If you want to reuse travis build instead of the ABI monitor build then travis should generate this configuration file somehow. This file describes locations of the install trees and source packages of the library versions to analyze. Once the configuration file is ready you need to execute these commands to build the analysis report:

abi-monitor -public-symbols openjpeg.json # additional analysis of exported symbols in header files under the install trees
abi-tracker -build openjpeg.json # build ABI timeline report
abi-tracker -deploy DIR openjpeg.json # publish all reports to DIR

Thank you.

**Comment by mayeut** [comment]
@detonin,

I can't get abi-tracker to generate a proper incremental result. So it's best to keep this separate for now (I think).

Maybe @aponomarenko has other directives than those in the mail pasted above.

**Comment by malaterre** [comment]
you need to store two abi files.then wget one of them (either 1.5.x or 2.x) during travis execution (pre build). not sure how to store files on github though.

**Comment by detonin** [comment]
shall be added in master branch and 1.5 branch

**Comment by mayeut** [comment]
I updated the build matrix to make an API check for every job (means push & pull request). Job will fail if API changes.
When not a pull request, the full timeline is built. However it's not being uploaded anywhere right now. Once figured out where it can be uploaded, there's still the fact that it needs to handle multiple branches.
I think we'll need one timeline per "allowed" branch (master, 1.5) and disable timeline upload for other branches.

:warning: The ABI check has been disabled. It seems that symbol visibility is an issue. The check is complaining about removed internal symbols. Those symbols are not marked as hidden with `OPJ_LOCAL`. In fact, `OPJ_LOCAL` is never used. It might be a good idea to build with `-fvisibility=hidden` not to get bothered with this in future versions & activate the check again.

**Comment by detonin** [comment]
@mayeut compared to your last comment, I guess we can say that ABI-check is working now but only when built with -fvisibility=hidden. Is that right ?
 I leave the issue open until we find a way to upload compat reports somewhere.

**Comment by mayeut** [comment]
@detonin, I guess we can close this one now ? We might wan't to do something to update the tracker properly on release ?

**Comment by detonin** [comment]
@mayeut closing this one and creating a new one specifically for this release issue #803
