### ISSUE TITLE
Decompression does not work with sequential data source

### ISSUE THREAD

**Issue by smuehlst** [uclouvain/openjpeg#613]
I'm referring to the thread [Decompressing JPEG2000 from sequential input](https://groups.google.com/d/topic/openjpeg/KS-rcZuNQGM/discussion) on the OpenJPEG mailing list.

I want to embed OpenJPEG in an application that reads its data from a data source that is only accessible in a sequential manner. Therefore an opj_stream_t objects was constructed with opj_stream_create() and only the read and skip functions were supplied via opj_stream_set_read_function() and opj_stream_set_skip_function(). With this implementation the decompression of all JPEG 2000 images fails with the error "opj_j2k_apply_nb_tile_parts_correction error".

In the mailing list thread it was suggested to implement the seek function but only implement forward seeking, and that should work, only some features would be missing. I did that, returning OPJ_FALSE in the seek function if a backward seek was attempted, and this didn't change the  behavior.

This was tested with the current HEAD of the master branch, cf352af089bd6adc89130fa839c57779e4870e6f at the time of this writing.

**Comment by malaterre** [comment]
seek function requirement was added recently. There was no such thing in opj 2.0 and opj 2.1.0 release. Please make sure seek is not required.

**Comment by mayeut** [comment]
This seems to be related to the patch from PR #514 which fixes #254 .
Can you try using `-DOPJ_DISABLE_TPSOT_FIX:BOOL=YES` when running cmake and see if that changes anything ?

**Comment by smuehlst** [comment]
@mayeut: Yes, -DOPJ_DISABLE_TPSOT_FIX:BOOL=YES helps, then decompression works without having a seek function, thank you.
After reading  #254, do I understand it correctly that the tradeoff is that certain broken JPEG 2000 images produced by Adobe tools cannot be decompressed?

**Comment by mayeut** [comment]
I've commited a fix for the workaround of #254 not to be enable if no seek function is provided.
You should be able to build openjpeg without `-DOPJ_DISABLE_TPSOT_FIX:BOOL=YES` and still get a working streaming implementation.

Images that are affected by the bug described in #254 will be decoded with a quality loss.

**Comment by smuehlst** [comment]
@mayeut: I tested the fix, and yes, I can build openjpeg without -DOPJ_DISABLE_TPSOT_FIX:BOOL=YES now and I'm still getting a working streaming implementation, thank you.

**Comment by ideasman42** [comment]
Note, I ran into this issue `OPJ_DISABLE_TPSOT_FIX` worked. But the actual cause was my seek function was using `SEEK_CUR` instead of `SEEK_SET` behavior.
