### ISSUE TITLE
opj_malloc replacement

### ISSUE THREAD

**Issue by malaterre** [uclouvain/openjpeg#625]
Some section of the code rely on specific alignement using sentinel `__SSE2__`:

```
#ifdef __SSE2__
void opj_mct_encode(
    OPJ_INT32* restrict c0,
    OPJ_INT32* restrict c1,
    OPJ_INT32* restrict c2,
    OPJ_UINT32 n)
{
  OPJ_SIZE_T i;
  const OPJ_SIZE_T len = n;

  for(i = 0; i < (len & ~3U); i += 4) {
    __m128i y, u, v;
    __m128i r = _mm_load_si128((const __m128i *)&(c0[i]));
```

But opj_malloc.h header does not have logic to cope with this (based on totally different logic). I suggest:

1. Move most of the implementation code to c code
2. Provide a dummy implementation for 16 bytes alignement. See for example: http://stackoverflow.com/questions/227897/how-to-allocate-aligned-memory-only-using-the-standard-library
3. Make sure that opj_mct_encode_sse_version is only called when buffer is 16 bytes aligned.
4. Provide an opj_aligned_realloc !

**Comment by malaterre** [comment]
@detonin I am less convinced I need to implement (3). Technically the code in the branch now garantee that memory is 16 bytes aligned in all cases, instead of hoping the code is executed on x86_64. So I would like people to comment on my proposal now.

**Comment by mayeut** [comment]
@malaterre,

calloc implementation shall probably be updated too.
FYI, don't know if you've seen this but travis is failing for debug builds.

**Comment by malaterre** [comment]
@mayeut `opj_calloc` is there... what do you mean ? I've fix my typo in the `assert()` sorry for the mess.

**Comment by mayeut** [comment]
@malaterre I'll comment in your commit, it'll be easier I think.

**Comment by mayeut** [comment]
My bad for `opj_calloc`, I misread the code.

**Comment by mayeut** [comment]
Seems an aligned `realloc` is not needed after all. I kept it nevertheless.
Compilation with `-m32 -march=i686 -mfpmath=sse -msse2` now completes the test suite. With much closer results to x86_64 than without `-mfpmath=sse -msse2`, as one would expect. Still #135 though.
