### ISSUE TITLE
transition away from dev-utils

### ISSUE THREAD

**Issue by malaterre** [uclouvain/openjpeg#628]
this issue is to track comments from moving away from the old svn rep: dev-scripts now that we have travis and appveyor

**Comment by malaterre** [comment]
I believe was can just remove the whole dev-utils/ctest_scripts directory. the main point was the close integration with ctest and version control system. Now that appveyor and travis implicitly rely on git, there is no point in keeping them. Do we still have physical machine we would like to run nightly or continuous ?

**Comment by malaterre** [comment]
Evreything in dev-utils/scripts can be pretty much kept as-is. It contains the ABI from openjpeg 1.5 and 2.x. The script to generate the changelog should be updated (svn -> git). Do we still need the upload to sf.net ? I do not believe so.

**Comment by rouault** [comment]
There's no dev-utils directory as far as I can see
