### ISSUE TITLE
opj_compress and opj_decompress : get_next_file method uses hard-coded unix path separator

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#630]
In these lines:

`sprintf(infilename,"%s/%s",img_fol->imgdirpath,image_filename);`

and

`sprintf(outfilename,"%s/%s.%s",img_fol->imgdirpath,temp_ofname,img_fol->out_format);`

use the following code to replace hard coded separator:

`#ifdef _WIN32`
`const char* path_separator = "\\";`
`#else`
`const char* path_separator = "/";`
`#endif`

**Comment by mayeut** [comment]
@boxerab,

I'd rather see the following:
```c
#ifdef _WIN32
# define OPJ_PATH_SEPARATOR "\\"
#else
# define OPJ_PATH_SEPARATOR "/"
#endif
```

Then:
```c
sprintf(infilename,"%s" OPJ_PATH_SEPARATOR "%s",img_fol->imgdirpath,image_filename);
```
And
```c
sprintf(outfilename,"%s" OPJ_PATH_SEPARATOR "%s.%s",img_fol->imgdirpath,temp_ofname,img_fol->out_format);
```

In any case, doesn't Windows support forward slash separators ?

**Comment by stweil** [comment]
Yes, it does. Even old versions of MSDOS support "/".

**Comment by boxerab** [comment]
@mayeut  I agree.  And yes, the code works fine on windows, but I find the path names are confusing when debugging under windows: a mix of forward and backward slashes. Also, this fix is already partially implemented in opj_decompress; just need to add it in a few more places. A 10 minute fix.
