### ISSUE TITLE
Compilation fails without platform-supplied aligned malloc

### ISSUE THREAD

**Issue by smuehlst** [uclouvain/openjpeg#642]
When none of none of `posix_memalign()`, `memalign()` and `_aligned_malloc()` is available, compilation of the current HEAD revision 57996722371d07e9626a36330c3a7a453475d4fd fails.

Discussion is on the mailing list: [Building OpenJPEG without a platform-supplied aligned memory allocation function](https://groups.google.com/forum/#!topic/openjpeg/LHwfVV_mSIg).

**Comment by mayeut** [comment]
@smuehlst, I pushed a version that shall be ok. Tested on my side by forcing this definitions to be used.
Please close the issue if everything works on your side.

**Comment by smuehlst** [comment]
@mayeut: Thanks for the comments and for the update to my implementation. It works fine for me. The only issue is that there's a compiler warning about pointer arithmetic with void * pointers.

I created pull request #644 with a fix for the warning.

**Comment by mayeut** [comment]
@smuehlst, I just merged your PR. Should be ok without warnings now.

**Comment by smuehlst** [comment]
@mayeut: Thanks, all is good now, closing this issue.
