### ISSUE TITLE
building mj2 binaries fails

### ISSUE THREAD

**Issue by bctvigil** [uclouvain/openjpeg#652]
I'm doing the following:

git clone https://github.com/uclouvain/openjpeg.git
cd openjpeg
cmake . -DBUILD_CODEC:bool=on -DBUILD_MJ2:bool=on
make

Make files part way in:

...
Scanning dependencies of target opj_mj2_compress
[ 83%] Building C object src/bin/mj2/CMakeFiles/opj_mj2_compress.dir/opj_mj2_compress.c.o
In file included from /home/tvigil/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:35:
[ 83%] Building C object src/bin/mj2/CMakeFiles/opj_mj2_compress.dir/opj_mj2_compress.c.o
In file included from /home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:35:
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:141: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:141: warning: its scope is only this definition or declaration, which is probably not what you want
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:146: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:274: warning: ‘struct opj_event_mgr’ declared inside parameter list
In file included from /home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:35:
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:284: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:292: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:301: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:329: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:338: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:347: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:356: warning: ‘struct opj_event_mgr’ declared inside parameter list
/home/me/projects/openjpeg/src/lib/openjp2/cio.h:365: warning: ‘struct opj_event_mgr’ declared inside parameter list
In file included from /home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:36:
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:557: error: expected specifier-qualifier-list before ‘opj_procedure_list_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:600: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:618: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:633: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:664: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:690: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:710: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:779: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:785: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:790: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:807: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:814: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:829: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/j2k.h:837: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
In file included from /home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:37:
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:218: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:249: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:271: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:285: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:296: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:312: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:321: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:331: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:346: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:372: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:389: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:407: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
In file included from /home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:37:
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:440: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:448: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
/home/me/projects/openjpeg/src/lib/openjp2/jp2.h:457: error: expected declaration specifiers or ‘...’ before ‘opj_event_mgr_t’
In file included from /home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:38:
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:149: error: expected specifier-qualifier-list before ‘opj_common_ptr’
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:230: error: expected specifier-qualifier-list before ‘opj_common_ptr’
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:309: error: expected ‘)’ before ‘_’ token
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:315: error: expected declaration specifiers or ‘...’ before ‘opj_cio_t’
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:320: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:339: error: expected declaration specifiers or ‘...’ before ‘opj_cio_t’
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:344: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘_’ token
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:365: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘mj2_encode’
/home/me/projects/openjpeg/src/lib/openmj2/mj2.h:385: error: expected declaration specifiers or ‘...’ before ‘opj_cio_t’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c: In function ‘give_progression’:
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:197: error: ‘LRCP’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:197: error: (Each undeclared identifier is reported only once
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:197: error: for each function it appears in.)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:201: error: ‘RLCP’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:205: error: ‘RPCL’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:209: error: ‘PCRL’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:213: error: ‘CPRL’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:215: error: ‘PROG_UNKNOWN’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c: In function ‘main’:
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:230: error: ‘opj_event_mgr_t’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:230: error: expected ‘;’ before ‘event_mgr’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:231: error: ‘opj_cio_t’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:231: error: ‘cio’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:242: error: ‘opj_cinfo_t’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:242: error: ‘cinfo’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:243: error: ‘opj_bool’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:243: error: expected ‘;’ before ‘bSuccess’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:257: error: ‘ENUMCS_SYCC’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:264: error: ‘event_mgr’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:682: error: ‘opj_common_ptr’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:682: error: expected ‘)’ before ‘cinfo’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:687: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:688: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:690: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:695: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:696: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:697: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:698: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:710: error: expected ‘)’ before ‘movie’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:713: error: too many arguments to function ‘mj2_write_ftyp’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:726: error: ‘opj_mj2_t’ has no member named ‘num_stk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:726: error: ‘opj_mj2_t’ has no member named ‘num_htk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:726: error: ‘opj_mj2_t’ has no member named ‘num_vtk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:728: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:737: error: ‘opj_mj2_t’ has no member named ‘tk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:738: error: ‘mj2_tk_t’ has no member named ‘num_chunks’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:738: error: ‘mj2_tk_t’ has no member named ‘num_samples’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:739: error: ‘mj2_tk_t’ has no member named ‘num_samples’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:740: error: ‘mj2_tk_t’ has no member named ‘depth’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:746: error: ‘mj2_tk_t’ has no member named ‘w’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:746: error: ‘mj2_tk_t’ has no member named ‘h’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:764: error: expected ‘)’ before ‘movie’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:770: error: ‘bSuccess’ undeclared (first use in this function)
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:770: error: too many arguments to function ‘opj_encode’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:783: error: ‘mj2_tk_t’ has no member named ‘sample’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:784: error: ‘mj2_tk_t’ has no member named ‘sample’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:785: error: ‘mj2_tk_t’ has no member named ‘chunk’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:814: error: ‘opj_mj2_t’ has no member named ‘cinfo’
/home/me/projects/openjpeg/src/bin/mj2/opj_mj2_compress.c:815: error: too many arguments to function ‘mj2_write_moov’
make[2]: *_\* [src/bin/mj2/CMakeFiles/opj_mj2_compress.dir/opj_mj2_compress.c.o] Error 1
make[1]: **\* [src/bin/mj2/CMakeFiles/opj_mj2_compress.dir/all] Error 2
make: **\* [all] Error 2

**Comment by stweil** [comment]
Confirmed for Debian GNU Linux Jessie where it also fails.
