### ISSUE TITLE
RESTART and BYPASS encoding modes are broken

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#674]
i.e. lossless encoding with either mode produces a lossy encoded file

Simple test:
1. lossless encode with command line flag    `-M 4`
2. decode and compare with original :  non-zero MSE between two images

**Comment by boxerab** [comment]
This is also true for BYPASS mode (M == 4)

**Comment by boxerab** [comment]
These modes have been broken for at least 6 years, probably forever.

**Comment by julienmalik** [comment]
Confirmed here.

By a strange coincidence, mode 1 and mode 4 are the only two modes who are generating the uninitialized read reported in #612. The others are valgrind-clean.

**Comment by rouault** [comment]
Fixed per https://github.com/uclouvain/openjpeg/pull/949

**Comment by rouault** [comment]
Fixed per https://github.com/uclouvain/openjpeg/pull/949
