### ISSUE TITLE
-t and -d command line flags for decode are not documented on OpenJPEG website

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#685]
https://github.com/uclouvain/openjpeg/wiki/DocJ2KCodec

See decompress

**Comment by mayeut** [comment]
I added missing options to `opj_decompress`. Can you check it's ok please ?

**Comment by boxerab** [comment]
Thanks. What do you mean by "left-up to bottom-up" ?

**Comment by mayeut** [comment]
It seems my mind played a trick on me when copy/pasting/reading from the code in `opj_decompress`. It corrected it to what needed to be understood: left-up to right-bottom.

**Comment by boxerab** [comment]
No problem. Looks good now.
