### ISSUE TITLE
-d flag is silently ignored when decoding a single tile

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#693]
Library always decodes the entire tile, no matter what is set with `-d`

**Comment by mayeut** [comment]
Does setting `-d`and `-t` arguments at the same time makes sense ?
I would think not. I'd rather see `-d` only decode part of the image in image coordinates, whatever the number of tiles needed. `-t` shall only decode the whole tile.
IMHO setting `-t` and `-d` shall result in an error or at least a warning saying that `-d`is ignored.

**Comment by boxerab** [comment]
Good point. Closing.

**Comment by mayeut** [comment]
Reopening with a different title. Changing from *-d flag is ignored when decoding a single tile* to *-d flag is __silently__ ignored when decoding a single tile*.
Minor but nonetheless a bug.
