### ISSUE TITLE
MQ Coder encode: Conditional jump or move depends on uninitialised value(s)

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#695]
http://my.cdash.org/viewDynamicAnalysisFile.php?id=3409924

      if (*mqc->bp == 0xff) {
		mqc->bp++;
		*mqc->bp = (OPJ_BYTE)(mqc->c >> 20);
		mqc->c &= 0xfffff;
		mqc->ct = 7;
	} else {

This is because mq->bp is initialized to one less than the actual data start address.
It could be possible for uninitialized memory to be equal to 0xFF, in which case there will be an error in the code stream. For lossless encoding, this could lead to lossy encoding.

An easy fix is to check if `mqc->bp < mqc->start` before entering the if statement.
On a modern CPU with branch prediction, there should be no performance hit.

**Comment by mayeut** [comment]
Is that the same than #612 ?

**Comment by boxerab** [comment]
yes, it looks like 612

**Comment by mayeut** [comment]
@boxerab closing this one as duplicate.

Follow-up in #612
