### ISSUE TITLE
install_name (still) not set on OS X

### ISSUE THREAD

**Issue by dmacks** [uclouvain/openjpeg#700]
Building version.2.1.tar.gz on OS X 10.11 using cmake-3.4.0, with b9a247b559e62e55f5561624cf4a19aee3c8afdc applied that claims to fix https://code.google.com/p/openjpeg/issues/detail?id=367

    % cmake -DCMAKE_INSTALL_PREFIX=/sw .
    % make
    % make install DESTDIR=/tmp/staging
    % otool -L /tmp/staging/sw/lib/libopenjp2.2.1.0.dylib
    /tmp/staging/sw/lib/libopenjp2.2.1.0.dylib:
    	libopenjp2.7.dylib (compatibility version 7.0.0, current version 2.1.0)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

That is, it's still not setting install_name to the runtime location of /sw/lib/libopenjp2.7.dylib

**Comment by mayeut** [comment]
Already fixed, as per comment on b9a247b559e62e55f5561624cf4a19aee3c8afdc by @dmacks
