### ISSUE TITLE
Stable Release?

### ISSUE THREAD

**Issue by markuskobler** [uclouvain/openjpeg#712]
I'm looking at integrating openjpeg and wondering what I should use as a stable release? Looks like there have been quite a few changes the last couple of years since the last offical release.

**Comment by stweil** [comment]
That depends on your requirements. I'd take the latest version from git (unless you are maintainer of a Linux distribution). That's what I do when building Tesseract with OpenJPEG support.

**Comment by markuskobler** [comment]
Great so it sounds like it is safe to assume master is stable enough to rely on.

**Comment by detonin** [comment]
indeed
