### ISSUE TITLE
Possible website problems due to Jekyll upgrade 

### ISSUE THREAD

**Issue by bitsgalore** [uclouvain/openjpeg#713]
Github recently upgraded Github Pages to Jekyll 3. This will most likely cause some issues after the next OJ website update. If this happens, the link below may provide a solution:

<https://github.com/openpreserve/jpylyzer/issues/89>

(I ran into this myself for the jpylyzer website; I expect the OpenJPEG site will be affected as well since it uses the same underlying structure.)

**Comment by detonin** [comment]
Thanks.
Apparently this upgrade did not affect the openjpeg website.
Closing
