### ISSUE TITLE
OpenJPEG fails to decode partial j2c where kdu succeeds

### ISSUE THREAD

**Issue by RyeMutt** [uclouvain/openjpeg#715]
OpenJPEG fails to decode the attached partial j2c that kdu_show succesfully decodes and renders.

Tested against OpenJPEG master branch.

opj_decompress reports the following error:

> Tile part length size inconsistent with stream length

[testimg1.zip](https://github.com/uclouvain/openjpeg/files/139945/testimg1.zip)

**Comment by boxerab** [comment]
What is a partial j2c ?

**Comment by CmdrCupcake** [comment]
I didn't really know what else to call it, but the software we work with(SecondLife opensource clients) decodes j2c files while they're downloading so that potentially only a piece of the file is available while it's decoding until full download is complete. When OpenJpeg 2.x tries to decode the partially downloaded file it outputs a garbled black/rainbow colored image, but OpenJpeg 1.5.0 works fine.

**Comment by duhaime** [comment]
@CmdrCupcake I'm working with a team that's trying to convert/restore some partial jp2s, and I'm wondering if the library you're using might be able to aid us in our quest (openjpeg fails to convert the images). Do you have a link to the source you're using to decode partial j2c files?

**Comment by CmdrCupcake** [comment]
The last version of openjpeg that could decode incomplete j2c streams was 1.5.0 in our usage(partially downloaded texture data for OpenSim/SecondLife protocol clients and servers). I believe the commercial kakadu library is also capable of this.

**Comment by duhaime** [comment]
Ah, thanks so much @CmdrCupcake! I don't think we're going to spring for the Kakadu license but I'm going to check out openjpeg@1.5.0. Thanks again for following up!

**Comment by jarrelscy** [comment]
2 years late.... but if you still care:
[https://github.com/jarrelscy/openjpeg](url)

I made some changes to the 2.3.1 repo that enable partial decoding.

**Comment by chafey** [comment]
I also implemented this here: https://github.com/uclouvain/openjpeg/pull/1251, not sure how it compares to @jarrelscy version

**Comment by Neopallium** [comment]
I updated @chafey PR.  #1407
