### ISSUE TITLE
opj_compress crops image (win) or creates a jp2 which cannot be decompressed (lin)

### ISSUE THREAD

**Issue by d462d91f96** [uclouvain/openjpeg#716]
`opj_compress -i input-test.png -o output-linux-master-20160223.jp2 -I -n 6 -p RPCL -t 1024,1024 -b 64,64 -r 2560,1280,640,320,160,80,40,20 -c [256,256],[256,256],[128,128],[128,128],[128,128],[128,128] -SOP -EPH`

Hi! Using these specific options, with an input image of this specific size and colour space (see examples.zip), there are following problems:
- The Windows 2.1.0 release creates a JP2, which is cropped at the bottom, without throwing an error. This JP2 is opj_decompress-able and viewable, but cropped.
- On Linux, a fresh build master creates a JP2 without throwing an error, which cannot be decompressed or viewed by opj_decompress, jasper, gimp, ...

This error won't occur with a blank image, there has to be some content at the bottom.

Best regards

[examples.zip](https://github.com/uclouvain/openjpeg/files/145269/examples.zip)

**Comment by rouault** [comment]
This is no longer reproducable with openjpeg 2.2.0. Likely due to the correction on the number of resolutions.
