### ISSUE TITLE
Shared library build broken on ubuntu

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#728]
I built the library with shared library option, and then ran

   `$ sudo make install`

and then

   `$ opj_compress`

This gives me an error about .so file not found. 

Switching to static build, opj_compress works fine.

**Comment by mayeut** [comment]
you need to run `ldconfig`after make install.
http://stackoverflow.com/a/17653893

**Comment by boxerab** [comment]
Thanks. Is this documented in INSTALL file?
