### ISSUE TITLE
Encoding the following file with 32x32 tiling produces jp2 image with artifact

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#737]
Encode the following TIF with the encoder settings

`-i b2_mono.tif -o b2_mono.jp2 -OutFor jp2 -t 32,32`

and the resulting jp2 image has an artifact on the right hand side of the image, about 15 pixels wide,
which corresponds to the width of the right-most tiles.

I also observed that the artifact is present for the default n=6 resolution levels, but not present
for n < 6.  So, it looks like a tile of width 15 with 6 resolutions levels is not being encoded properly, probably due to LL0 having zero width.

I also observed that if I tried to do a single tile encode of a 303x179 image with n = 9,
encode fails, complaining that the number of resolutions is too high. So, in the 32x32 tile
case, it looks like the code can't handle n=6 for the boundary tiles, of width 15.

So, to be consistent, encoder should reject these settings, just like it rejects single tile encodings when n is too large.

[b2_mono.zip](https://github.com/uclouvain/openjpeg/files/216356/b2_mono.zip)

**Comment by boxerab** [comment]
Happy Holidays

**Comment by rouault** [comment]
Can no longer reproduce. Likely fixed per 73d1510d473b7dcfccfdee57e0e511e6791d5091
