### ISSUE TITLE
API change since v2: opj_event_mgr_t not available

### ISSUE THREAD

**Issue by cchampet** [uclouvain/openjpeg#754]
Since [this commit](https://github.com/uclouvain/openjpeg/commit/a6a141d3262edfb741b564afadd5614089614858), the struct __opj_event_mgr_t__ is not available in the API.

Do you plan to fix it (deploy __event.h__ header file)? Or is there a new way to handle an event manager?

**Comment by mayeut** [comment]
Aren't the functions defined [here](https://github.com/uclouvain/openjpeg/blob/master/src/lib/openjp2/openjpeg.h#L1186) enough for your needs ?

**Comment by malaterre** [comment]
No news in 12 days, I guess OP did find a way. Closing.
