### ISSUE TITLE
FFMpeg will not link to 2.1.1 release built as shared library

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#766]
FFMPeg *will* link with the 2.1 release.

It seems that a recent change to visibility of symbols is the cause: if OPJ_STATIC is defined,
then API symbols are marked "hidden". However, FFMpeg always defines OPJ_STATIC when linking, even for dynamic builds. So, linking fails in this case.  

    #	if __GNUC__ >= 4
    #		if defined(OPJ_STATIC) /* static library uses "hidden" */
    #			define OPJ_API    __attribute__ ((visibility ("hidden")))
    #		else

The reason why FFMpeg always define OPJ_STATIC is because of mingw builds: mingw doesn't mangle names like gcc,

**Comment by malaterre** [comment]
I believe this is now solved upstream. Closing.

**Comment by szukw000** [comment]
Mathieu Malaterre wrote:

>I believe this is now solved upstream. Closing.

What kind of believed upstream do you mean?

winfried

libavcodec/libopenjpegdec.o: In function `libopenjpeg_decode_frame':
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:378: undefined reference to `opj_create_decompress'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:396: undefined reference to `opj_set_error_handler'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:397: undefined reference to `opj_set_warning_handler'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:398: undefined reference to `opj_set_info_handler'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:409: undefined reference to `opj_setup_decoder'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:414: undefined reference to `opj_stream_default_create'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:431: undefined reference to `opj_stream_set_read_function'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:432: undefined reference to `opj_stream_set_skip_function'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:433: undefined reference to `opj_stream_set_seek_function'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:435: undefined reference to `opj_stream_set_user_data'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:441: undefined reference to `opj_stream_set_user_data_length'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:443: undefined reference to `opj_read_header'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:372: undefined reference to `opj_create_decompress'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:554: undefined reference to `opj_image_destroy'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:556: undefined reference to `opj_stream_destroy'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:557: undefined reference to `opj_destroy_codec'
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:495: undefined reference to `opj_decode'
libavcodec/libopenjpegdec.o: In function `libopenjpeg_decode_init':
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:338: undefined reference to `opj_set_default_decoder_parameters'
libavcodec/libopenjpegdec.o: In function `libopenjpeg_static_init':
ffmpeg-3.1.3/libavcodec/libopenjpegdec.c:567: undefined reference to `opj_version'
libavcodec/libopenjpegenc.o: In function `libopenjpeg_encode_frame':
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:705: undefined reference to `opj_create_compress'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:716: undefined reference to `opj_set_error_handler'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:717: undefined reference to `opj_set_warning_handler'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:785: undefined reference to `opj_stream_destroy'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:786: undefined reference to `opj_destroy_codec'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:718: undefined reference to `opj_set_info_handler'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:724: undefined reference to `opj_setup_encoder'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:729: undefined reference to `opj_stream_default_create'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:757: undefined reference to `opj_stream_set_write_function'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:758: undefined reference to `opj_stream_set_skip_function'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:759: undefined reference to `opj_stream_set_seek_function'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:761: undefined reference to `opj_stream_set_user_data'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:768: undefined reference to `opj_start_compress'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:769: undefined reference to `opj_encode'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:770: undefined reference to `opj_end_compress'
libavcodec/libopenjpegenc.o: In function `libopenjpeg_encode_close':
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:798: undefined reference to `opj_image_destroy'
libavcodec/libopenjpegenc.o: In function `libopenjpeg_encode_init':
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:307: undefined reference to `opj_set_default_encoder_parameters'
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:384: undefined reference to `opj_image_destroy'
libavcodec/libopenjpegenc.o: In function `mj2_create_image':
ffmpeg-3.1.3/libavcodec/libopenjpegenc.c:287: undefined reference to `opj_image_create'
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/../../../../x86_64-slackware-linux/bin/ld: libavcodec/libavcodec.so.57: hidden symbol `opj_setup_decoder' isn't defined
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/../../../../x86_64-slackware-linux/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make: *** [libavcodec/libavcodec.so.57] Error 1

**Comment by szukw000** [comment]
@malaterre , I have made a test.

FFMPEG compiles bug-free with openjpeg-1.5.x .

So I made a copy of openjpeg2-git-2016-09-21-1/src/lib/openjp2/openjpeg.h . In openjpeg.h I
removed the lines between 79 and 108.

Then I inserted at line 79 the respective lines of openjpeg-1.5.3-1/libopenjpeg/openjpeg.h,
compiled and installed.

Now I was able to compile and install ffmpeg-3.1.3 bug-free.

winfried

**Comment by szukw000** [comment]
@malaterre , I used the following compilers:

gcc (GCC) 5.3.0 (Linux 4.7.3)
MSVC 19.0.24210.0 (WIN7-64, Community 2015)
gcc (Debian 4.9.2-10) 4.9.2 (PPC-64)

winfried

**Comment by malaterre** [comment]
@szukw000 you should instead follow instructions from: https://github.com/uclouvain/openjpeg/issues/802#issuecomment-234606028
