### ISSUE TITLE
Potential overflow when precision is larger than 32

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#781]
The JPEG 2000 standard allows up to 38 bit precision.

There are many places in the code of the form

`(1 <<  image->comps[3].prec)`

which will overflow for large precision.

**Comment by boxerab** [comment]
Happy Holidays

**Comment by rouault** [comment]
Precision limited now to 31 bit per e03e9474667e5117341351699f0b1dbb06f93346
