### ISSUE TITLE
unsigned int16 on Solaris 11.2/sparc

### ISSUE THREAD

**Issue by joernclausen** [uclouvain/openjpeg#796]
Compiling openjpeg on Solaris 11.2/sparc using GCC 4.7.5 fails on "u_int16_t" in src/bin/jp2/convert.c. Changing this to "uint16_t" seems to fix the problem.

**Comment by mayeut** [comment]
This is already fixed in release 2.1.1 & master

**Comment by stweil** [comment]
It was only fixed for jp2, but is still open for jpwl. I sent a PR which fixes it there, too.
