### ISSUE TITLE
Add dashboard with static lib

### ISSUE THREAD

**Issue by malaterre** [uclouvain/openjpeg#804]
If I read correctly issue #802 it got under our radar because no dashboard is actually doing the GCC visibility + static lib building. Would be nice to have it to prevent such regression in the future.

**Comment by mayeut** [comment]
@malaterre, If I'm not mistaken, the static library builds/link just fine. However, defining `-DOPJ_STATIC` while linking against the shared library fails. I think this is an invalid usage but maybe I'm missing something ?

**Comment by malaterre** [comment]
ACK. I failed to understand the actual issue. Thanks for the clarification.
