### ISSUE TITLE
Security Advisory for OpenJPEG

### ISSUE THREAD

**Issue by regiwils** [uclouvain/openjpeg#810]
Searching point of contact for reporting security issue with openjpeg product.

**Comment by malaterre** [comment]
I would try info at openjpeg.org

**Comment by regiwils** [comment]
Thanks

**Comment by attritionorg** [comment]
With the release of 2.1.2 that fixes this, can you link to the fixing commit please?

**Comment by mayeut** [comment]
Fixed by 734d57d

**Comment by attritionorg** [comment]
Thanks!
