### ISSUE TITLE
openjpeg-1.5.3 fails to compile

### ISSUE THREAD

**Issue by szukw000** [uclouvain/openjpeg#830]
I had to compile openjpeg-1.5 and found that 1.5.3 does not compile.
Attached is a patch.

winfried
[j2k_to_image.c.dif.zip](https://github.com/uclouvain/openjpeg/files/466205/j2k_to_image.c.dif.zip)

**Comment by malaterre** [comment]
Hi winfried, thanks for the patch. I believe OPJ 1.5.3 is now very old and completely unmaintained (affected by dozen of CVEs and bugs). I would simply close this bug, anyone still using 1.5.3 would still be able to find your patch anyway. @detonin comments ?

**Comment by detonin** [comment]
hello, latest 1.5.x release is 1.5.2. 
v1.5.3 will most probably never be released... However the branch 1.5 shall at least compile, which I just tested on MacOSX and it seems to work fine.

**Comment by rouault** [comment]
Closing, as 1.x version is not maintained anymore.
If you need this issue resolved, please switch instead to latest version where its is likely already fixed.
https://groups.google.com/d/msg/openjpeg/w2I6qPOw_KA/S85qgiy_AgAJ
