### ISSUE TITLE
BIG_ENDIAN bug in jpwl.c

### ISSUE THREAD

**Issue by szukw000** [uclouvain/openjpeg#839]
I compiled openjpeg2-git-2016-08-21  on a PPC64 machine:

Linux g5 3.16.0-4-powerpc64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) ppc64 GNU/Linux

The following error was reported:

---

/home/sources/LIB/OPENJPEG/openjpeg2-git-2016-08-21/src/bin/jpwl/convert.c:190:15: error:
unknown type name 'uint16_t'
 static inline uint16_t swap16(uint16_t x)

/home/sources/LIB/OPENJPEG/openjpeg2-git-2016-08-21/src/bin/jpwl/convert.c:190:31: error:
unknown type name 'uint16_t'
 static inline uint16_t swap16(uint16_t x)

make[2]: **\* [src/bin/jpwl/CMakeFiles/opj_jpwl_compress.dir/convert.c.o] Error 1
make[1]: **\* [src/bin/jpwl/CMakeFiles/opj_jpwl_compress.dir/all] Error 2
make: **\* [all] Error 2

---

The report was triggered because of:
# ifdef OPJ_BIG_ENDIAN

static inline uint16_t swap16(uint16_t x)
{
    return(((x & 0x00ffU) << 8) | ((x & 0xff00U) >> 8));
}
# endif

The patch is attached.

winfried
[jpwl-dif.txt](https://github.com/uclouvain/openjpeg/files/471562/jpwl-dif.txt)

**Comment by stweil** [comment]
The patch looks good. Do you want to send a pull request?

Using `byteswap.h` and the `bswap_16` macro would be an alternative solution.
