### ISSUE TITLE
Updates for Doxygen to suppress warnings

### ISSUE THREAD

**Issue by szukw000** [uclouvain/openjpeg#849]
These changes suppress warnings for '-DBUILD_DOC:bool=on'.

winfried
[doxygen-dif.txt.zip](https://github.com/uclouvain/openjpeg/files/489689/doxygen-dif.txt.zip)

**Comment by szukw000** [comment]
I wanted to make a pull request but failed:

remote: Permission to uclouvain/openjpeg.git denied to szukw000.
fatal: unable to access 'https://github.com/uclouvain/openjpeg/':  \
The requested URL returned error: 403

winfried

**Comment by stweil** [comment]
Did you add your commit to [your clone of OpenJPEG](https://github.com/szukw000/openjpeg)?

**Comment by szukw000** [comment]
@stweil ,
no. Then I saw my error and created a new request. But failed anew, I suppose.
I do not understand github.

winfried

**Comment by stweil** [comment]
You start a pull request by adding your commit to your cloned version, for example to your master branch. Then the [web page of your clone](https://github.com/szukw000/openjpeg) offers a button to create a pull request for that commit. The rest is really easy.
