### ISSUE TITLE
opj_compress with lossy compression results in strange pixel values

### ISSUE THREAD

**Issue by vroeyt** [uclouvain/openjpeg#851]
When calling opj_compress with lossy compression enabled, I got output pixel values that are completely diffferent than the input pixels. I used the following command (in this case lossy compression with ratio 5):

opj_compress -I -r 5 -i test.tif -o test.jp2

For example, the pixel at position (0,0) in the original TIFF image "test.tif" has pixel value 97, while the corresponding pixel in the output jpeg2000 image "test.jp2" has value 62069. Once could expect that the compressed pixel values are slightly different than the original pixel values, but such a huge difference is strange and unexplainable to me. 

Even when I specify a lower compression rate (e.g. rate 2), the huge difference in pixel values remains. When I use lossless compression ("opj_compress -i test.tif -o test.jp2"), the result is as expected (output = input). The compression rate I got when using lossless compression is approx. 3,85.

Attached the test files "test.tif" and "test.jp2". I'm using openjpeg-v2.1.1.

[testdata.zip](https://github.com/uclouvain/openjpeg/files/492596/testdata.zip)

**Comment by rouault** [comment]
This has been solved in trunk, presumably by 73d1510d473b7dcfccfdee57e0e511e6791d5091
