### ISSUE TITLE
Denial of service (crash) when decoding an illegal JPEG2000 image file v2.1.2 (2017-03)

### ISSUE THREAD

**Issue by PeteACoordinator** [uclouvain/openjpeg#879]
Summary of the issue:
The opj_dump and opj_decompress utilities crash (segmentation fault) when parsing an illegal JPEG2000 image file. Any program which uses the OpenJPEG library will also crash when parsing such specially-crafted inputs.
Explanation:
The attached poc1.zip (password: infected) contains the specially crafted image file poc1.j2k which causes this issue. Example:
$ ./opj_dump -i poc1.j2k
[poc1.zip](https://github.com/uclouvain/openjpeg/files/685662/poc1.zip)
[vulnerability-disclosure-openjpeg.docx](https://github.com/uclouvain/openjpeg/files/685663/vulnerability-disclosure-openjpeg.docx)

**Comment by rouault** [comment]
probably fixed per 16aeb9282f6b3877aa8365c461ba8d3d1338adae
