### ISSUE TITLE
Pull request #882 superseeds #869 and #873

### ISSUE THREAD

**Issue by szukw000** [uclouvain/openjpeg#883]
@mayeut , @detonin ,

the request #882 shall be - for the present - my last one to protect agains AFL havocs. 

Others may follow if #882 has been accepted and applied.

winfried

**Comment by szukw000** [comment]
@detonin, @mayeut,

I had to pause a while because I had been knocked down by a severe flu.

The attached TXT file contains some examples with an unchanged library
(openjpeg2-2017-02-01) and a changed library (openjpeg2-2017-01-08).

The following file is contained in 'crashes-openjpeg-2.1.1.tar.gz':

openjpeg2-2017-02-01/BUILD/bin/opj_decompress -o out.png
 -i /tmp/000-009/id:000001,sig:11,src:001071+003290,op:splice,rep:32

[INFO] Start to read j2k main header (385).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Psot value of the current tile-part is equal to zero, we assuming it is the last tile-part of the codestream.
[INFO] Header of tile 1 / 1 has been read.
[INFO] Tile 1/1 has been decoded.
Segmentation fault

WHEREAS:

openjpeg2-2017-01-08/BUILD/bin/opj_decompress -o out.png
 -i /tmp/000-009/id:000001,sig:11,src:001071+003290,op:splice,rep:32

[INFO] Start to read j2k main header (385).
[ERROR] Error with SIZ marker: IMAGE w(155) h(265) vs. TILE w(400) h(315)
[ERROR] Marker handler function failed to read the marker segment
ERROR -> opj_decompress: failed to read the header

      -----

E.g. for the image 'input/nonregression/issue726.j2k' I get:

gm animate
 /backup/2017-01-28-openjpeg-data-master/input/nonregression/issue726.j2k

jpc_dec_decodepkts failed
gm animate: Unable to decode image file (/backup/2017-01-28-openjpeg-data-master/input/nonregression/issue726.j2k).

kdu_expand -o out.tif
 -i /backup/2017-01-28-openjpeg-data-master/input/nonregression/issue726.j2k

Consumed 1 tile-part(s) from a total of 97 tile(s).
Consumed 328 codestream bytes (excluding any file format) = 0.042268 bits/pel.
Processed using the multi-threaded environment, with
    6 parallel threads of execution

Geometry of the file 'out.tif' is 5x12416.

      -----

IrfanView-4.44 and kdu_show.exe-7.9.0 both show under WIN7 an image
with geometry 5x12416. IrfanView shows a black, kdu_show a white
image.

'out.tif' has stripes at the beginning. 'animate' shows a 2 channel
GrayscaleAlpha image; 'gm animate' shows a 1 channel Gray image.

      -----

Does any good reason exist NOT to reject a file when the tile geometry
exceeds the image geometry?

My patch for #883 contains a bug: the patch was for RGB images only,
ignoring the files issue411-ycc422.jp2 and issue411-ycc420.jp2.

winfried

[changed-and-unchanged-library.txt](https://github.com/uclouvain/openjpeg/files/748589/changed-and-unchanged-library.txt)

**Comment by szukw000** [comment]
@detonin , @mayeut ,

I am ready for another AFL patch. But one problem remains.

'make Experimental' for the changed library is:

99% tests passed, 10 tests failed out of 1621

Total Test time (real) = 285.31 sec

The following tests FAILED:
    1171 - NR-DEC-issue104_jpxstream.jp2-33-decode-md5 (Failed)
    1224 - NR-DEC-broken.jpc-73-decode (Failed)
    1225 - NR-DEC-issue226.j2k-74-decode (Failed)
    1226 - NR-DEC-issue226.j2k-74-decode-md5 (Failed)
    1348 - NR-DEC-p1_06.j2k-156-decode (Failed)
    1349 - NR-DEC-p1_06.j2k-156-decode-md5 (Failed)
    1364 - NR-DEC-p1_06.j2k-164-decode (Failed)
    1365 - NR-DEC-p1_06.j2k-164-decode-md5 (Failed)

    1366 - NR-DEC-p1_06.j2k-165-decode (Failed)
    1367 - NR-DEC-p1_06.j2k-165-decode-md5 (Failed)

'make Experimental' for the unchanged library does count the
errors from 1171 upto 1365. Errors 1366 and 1367 are missing.

'tools/travis-ci/knownfailures-all.txt' does list only:

 NR-DEC-p1_06.j2k-164-decode
 NR-DEC-p1_06.j2k-164-decode-md5

Do you know what kind of error I must look for?

winfried

**Comment by rouault** [comment]
Closing this one since it was later superseded by #895
