### ISSUE TITLE
Undefined shift in opj_get_all_encoding_parameters

### ISSUE THREAD

**Issue by npm1** [uclouvain/openjpeg#885]
In opj_get_all_encoding_parameters, there should be some checked to ensure that 1u << (l_pdx + l_level_no) and 1u << (l_pdy + l_level_no) are not undefined shifts on corrupted files. But I'm not sure what the correct way to fix this is. I'll share a sample file that exhibits the problem on request.

**Comment by rouault** [comment]
Was fixed per a88cbb6a0b3539461dfb29922102953b7a7fc3a7
