### ISSUE TITLE
Wrong decoding of YUV420 image

### ISSUE THREAD

**Issue by vinod-mv** [uclouvain/openjpeg#887]
Hello,
    I am encoding a yuv420 file by issuing the following command.

../../Bins/opj_compress -F 3840,1920,3,8,u@1x1:2x2:2x2 -i ../Data/yuv420/Drivin_3840x1920_8bit_420.raw -o out.jp2 

I am then decoding the encoded file by issuing the following command
../../Bins/opj_decompress -i out.jp2 -o out.raw

A part of the output i am getting from the decoder is:

Raw image characteristics: 3 components
Component 0 characteristics: 3840x1920x8 unsigned
Component 1 characteristics: 3840x1920x8 unsigned
Component 2 characteristics: 3840x1920x8 unsigned

This is strange because component 1 and 2 should be subsampled. Isn't it?

When viewing the output raw file. The colours are all wrong. Am I doing something obviously wrong. I have the checked the input YUV and I can confirm that it is a 420 yuv file.

**Comment by vinod-mv** [comment]
I have solved the problem. I was expecting the decoder to give a raw 420 yuv file if the switches -force-rgb and upsample is not given in the command line. But the decoder defaults force-rgb and upsample flags to be 1 and was returning a RGB 444 output.

**Comment by rouault** [comment]
Closing since reporter solved the issue

**Comment by visionbike** [comment]
Hi @vinod-mv ,
Because you say that you solve this problem, can you instruct me how to decode raw 420 yuv. I don't know how to do.
Thank you.
