### ISSUE TITLE
Encoder crashes on small images

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#901]
For example : file c1p0_12_0.pgx from conformance suite

**Comment by boxerab** [comment]
Seems that tile buffer is not big enough, and bio fails.

**Comment by rouault** [comment]
Can you give more details on how to reproduce ? The following works fine:
```bin/opj_compress -i ../data/baseline/conformance/c1p0_12_0.pgx -o out.jp2 -n 1```

**Comment by boxerab** [comment]
Well then, it looks like this has been fixed. Closing.
