### ISSUE TITLE
Undefined-shift in opj_j2k_read_siz

### ISSUE THREAD

**Issue by npm1** [uclouvain/openjpeg#902]
On j2k.c, line 2146, we have the following assignment, where tmp is read from file:
`l_img_comp->prec = (tmp & 0x7f) + 1;`
Shortly after, line 2161, we enter error on the following:
`if( l_img_comp->prec > 38) `
Later on in the same method, line 2316, we do:
`p_j2k->m_specific_param.m_decoder.m_default_tcp->tccps[i].m_dc_level_shift = 1 << (l_image->comps[i].prec - 1);`
Thus if prec is greater than 31, we will get undefined shift. I would suggest we change the if statement on line 2161 to:
`if( l_img_comp->prec > 31) `
This not only avoids the undefined shift, it also makes sense because prec is the number of precision bits. Another option would be to truncate prec to 31.

**Comment by rouault** [comment]
Was fixed per e03e9474667e5117341351699f0b1dbb06f93346
