### ISSUE TITLE
encoder: lossless encode with BYPASS(1) + RESTART(4) mode results in lossy image

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#906]
PSNR is around 50, so there seems to be quite a bit of loss.

There already is an issue open regarding BYPASS mode, but I think we still need this issue, since RESTART changes how raw passes are terminated - even with BYPASS fixed, the combination may still be broken.

**Comment by rouault** [comment]
Fixed per https://github.com/uclouvain/openjpeg/pull/949
