### ISSUE TITLE
Process for reporting security bugs

### ISSUE THREAD

**Issue by Google-Autofuzz** [uclouvain/openjpeg#920]
Hello OpenJpeg,

As part of our fuzzing efforts at Google, we are interested in understanding the process for reporting potential security issues to your project in a private manner.  Could you please advise us if there is a private tracker for these kinds of bugs, or if you prefer them filed in a publicly visible way?  

Thanks!

**Comment by detonin** [comment]
Hi,

You can send a description of such potential security issues to info@openjpeg.org.

Many thanks,

Antonin
