### ISSUE TITLE
Dose the openjpeg support the ROI ?

### ISSUE THREAD

**Issue by BoZhuan** [uclouvain/openjpeg#924]

**Comment by novalain** [comment]
Nope not yet, however in the latest blog post they say that region-of-interest decoding will be prioritized soon: http://www.openjpeg.org/2017/04/27/Faster-OpenJPEG-is-on-track

**Comment by rouault** [comment]
> http://www.openjpeg.org/2017/04/27/Faster-OpenJPEG-is-on-track

The wording in the announcement is a bit inaccurate. Instead of region-of-interest it should have read "window-of-interest" (ie a rectangular part of the image, not the JPEG2000 specific ROI trick).

ROI decoding is supported (at least there's code for it)

**Comment by rouault** [comment]
github tickets should be reserved for issue reporting, not questions. https://groups.google.com/forum/#!forum/openjpeg is the appropriate medium. Closing

**Comment by davidbernat** [comment]
@rouault What is the JPEG2000 specific ROI trick you refer to?  And, what is the current state of the art window-of-interest read-ready implementation available? Thanks,
