### ISSUE TITLE
Getting compressed data from image

### ISSUE THREAD

**Issue by novalain** [uclouvain/openjpeg#933]
Is there any way to get the raw compressed data of an image as an array of bytes? 

In my case it's a single-tile grayscale image. I want this feature to be able to pass on the raw compressed data to a GPU decoder (that has no support for reading this from a .jp2), and benchmark the results.

**Comment by boxerab** [comment]
I'm curious : which GPU decoder for J2K doesn't support JP2 file format ?

**Comment by novalain** [comment]
This one: http://www.cse.cuhk.edu.hk/~ttwong/demo/dwtgpu/dwtgpu.html. Their GPU module seems to take in a `float*` buffer which represents the raw compressed bytes and a `width` and `height` of the output image

**Comment by rouault** [comment]
github tickets should be reserved for issue reporting, not questions.  https://groups.google.com/forum/#!forum/openjpeg is the appropriate medium. Closing

**Comment by boxerab** [comment]
@novalain 2006, man :)  I would recommend not wasting your time on that.  Focus on multi-core machines such as the upcoming Ryzen threadripper : 16 cores, 32 threads.

**Comment by novalain** [comment]
@boxerab yeah I know it's old :) but the shader/GPU decoding really makes a lot of sense for my use case. I decode and display these images in my real time application and consequently I'll be uploading images to the GPU anyways. If I could do the decoding there it would be a huge speed up :) (otherwise I get that the transfer speed of the image data to the GPU is normally the bottleneck, and why multi-core machines are preferred).

**Comment by boxerab** [comment]
Well, you might want to post on the news group, as @rouault suggested. Many years ago, there was someone who kept promising to open source their GPU wavelet code, which was integrated with OpenJPEG. I kept asking, but he never quite got around to doing it.

**Comment by novalain** [comment]
Yep. Thanks, I posted in that group. If I have time I'll also dig into the .jp2 format and the openjpeg source code to see if I can understand how to access the byte stream of the image, it doesn't seem like there is an easy way to do it right now.
