### ISSUE TITLE
How to initialize DEBUG_PROFILE in color.c?

### ISSUE THREAD

**Issue by Jamaika1** [uclouvain/openjpeg#958]
I would like openjpeg to read info color profiles ICC from tif(f) files. I see that there are some implementations for data import. However, the data isn't definited when compiled in gcc 6/7/8. Is this an unfinished development path?
```
#ifdef DEBUG_PROFILE
    FILE *icm = fopen("debug.icm", "wb");
    fwrite(image->icc_profile_buf, 1, image->icc_profile_len, icm);
    fclose(icm);
#endif

```
```
#ifdef DEBUG_PROFILE
        fprintf(stderr, "%s:%d: color_apply_icc_profile\n\tICC Profile has unknown "
                "output colorspace(%#x)(%c%c%c%c)\n\tICC Profile ignored.\n",
                __FILE__, __LINE__, out_space,
                (out_space >> 24) & 0xff, (out_space >> 16) & 0xff,
                (out_space >> 8) & 0xff, out_space & 0xff);
#endif
```

**Comment by ValZapod** [comment]
No, this is for debugging purposes.

**Comment by ValZapod** [comment]
Just uncomment this line https://github.com/uclouvain/openjpeg/blob/491299eb073c80602ca8ee333303a31a581d3fa8/src/bin/common/color.c#L456
