### ISSUE TITLE
How to identify if a jpeg 2000 file was created lossy or lossless?

### ISSUE THREAD

**Issue by netx123** [uclouvain/openjpeg#967]
I need to identify if a jpeg 2000 file is lossy or lossless is there any way to achieve this?

For jpeg files it was easily a case of checking the SOF markers (0xC0 = Lossy, OxC3 = Lossless)

But how can I determine this for jpeg 2000 files?

**Comment by rouault** [comment]
GitHub issues are not for questions. There's the mailing list for that.

To answer your question, if you use opj_dump, when you have qmfbid=1 in a component, its lossless. If qmfbid=0 then it is lossy

**Comment by DavidUnderdown** [comment]
You might like to take a look at [Jpylyzer](https://github.com/openpreserve/jpylyzer) which extracts various info from JP2s
