### ISSUE TITLE
the input images can't be Interlaced rgb format?

### ISSUE THREAD

**Issue by lugui2009** [uclouvain/openjpeg#971]
I found that the images of Interlaced rgb format can't work right,and I have to  seperate the rgb images to red channel ,blue channel and green channel seperately.Must I do the seperation?And how to work right when using Interlaced rgb format? thank you .

**Comment by rouault** [comment]
This issue tracker isn't designed for questions. The mailing list https://groups.google.com/forum/#!forum/openjpeg or other forums are better for that.
