### ISSUE TITLE
Decode fails for JP2s with ICC profile

### ISSUE THREAD

**Issue by bitsgalore** [uclouvain/openjpeg#981]
I tried to decompress the following JP2 to TIF using the latest (2.2.0) OpenJPEG release:

<https://github.com/openpreserve/format-corpus/raw/master/jp2k-test/icc/balloon_eciRGBv2_aware.jp2>

Command:

    opj_decompress -i balloon_eciRGBv2_aware.jp2 -o balloon_eciRGBv2_aware.tif

This resulted in the following error (no output image was written):

    [INFO] Stream reached its end !
    /home/johan/openjpeg-v2.2.0-linux-x86_64/bin/opj_decompress: symbol lookup error: /home/johan/openjpeg-v2.2.0-linux-x86_64/bin/opj_decompress: undefined symbol: opj_image_data_alloc

I got the same result with this image:

<https://github.com/openpreserve/format-corpus/raw/master/jp2k-test/icc/balloon_eciRGBv2_ps_kduplugin.jp2>

Though I'm not 100% sure on this, I suspect the error has something to do with the fact that the JP2 contains an embedded ICC profile. For example, below image (which is similar except that it has no ICC profile) is converted to TIFF without any problem:

<https://github.com/openpreserve/format-corpus/raw/master/jp2k-test/resolution/balloon_aware.jp2>

(Note: I'm using the Linux binaries under Linux Mint 18)

**Comment by rouault** [comment]
I'm pretty sure the issue must be that your /home/johan/openjpeg-v2.2.0-linux-x86_64/bin/opj_decompress: symbol lookup error: /home/johan/openjpeg-v2.2.0-linux-x86_64/bin/opj_decompress links against a different version of libopenjp2. Try setting export LD_LIBRARY_PATH=/home/johan/openjpeg-v2.2.0-linux-x86_64/lib

**Comment by bitsgalore** [comment]
@rouault You're completely right, I'd forgotten there even *was* an old version on my machine, but after making the changes it now works perfectly. Also I'm *really* impressed with the improvement in decoding speed! Thanks for pointing this out, I'll now close this issue.
