### ISSUE TITLE
freeze with a crafted bmp

### ISSUE THREAD

**Issue by asarubbo** [uclouvain/openjpeg#996]
The attached testcase freezes the process without exit.

command to reproduce:
```
opj_compress -r 20,10,1 -jpip -EPH -SOP -cinema2K 24 -n 1 -i $FILE -o null.j2k
```
[2.hangs.zip](https://github.com/uclouvain/openjpeg/files/1233701/2.hangs.zip)

**Comment by asarubbo** [comment]
With the current master I still get the freeze with another file
[11.hangs.zip](https://github.com/uclouvain/openjpeg/files/1233775/11.hangs.zip)

**Comment by asarubbo** [comment]
Another file which freezes:
[15.hangs.zip](https://github.com/uclouvain/openjpeg/files/1233843/15.hangs.zip)

**Comment by rouault** [comment]
The issue with 11.hangs.zip and 15.hangs.zip is completely different; They are BMP files of huge dimensions. So compressions takes a lot of time / memory (potentially crashing the process)

$ file ../11.hangs.bmp
../11.hangs.bmp: PC bitmap, Windows 3.x format, 16711929 x 1 x 8

$ file ../15.hangs.bmp
../15.hangs.bmp: PC bitmap, Windows 3.x format, 369098753 x 1 x 4

**Comment by asarubbo** [comment]
if you think I need to open a separate bug I will.
